// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module top_tx_adding_pilot (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        user_id0,
        user_id1,
        temp1_re397_dout,
        temp1_re397_empty_n,
        temp1_re397_read,
        temp1_im398_dout,
        temp1_im398_empty_n,
        temp1_im398_read,
        temp2_re399_din,
        temp2_re399_full_n,
        temp2_re399_write,
        temp2_im400_din,
        temp2_im400_full_n,
        temp2_im400_write
);

parameter    ap_ST_fsm_state1 = 12'd1;
parameter    ap_ST_fsm_state2 = 12'd2;
parameter    ap_ST_fsm_state3 = 12'd4;
parameter    ap_ST_fsm_state4 = 12'd8;
parameter    ap_ST_fsm_state5 = 12'd16;
parameter    ap_ST_fsm_state6 = 12'd32;
parameter    ap_ST_fsm_state7 = 12'd64;
parameter    ap_ST_fsm_state8 = 12'd128;
parameter    ap_ST_fsm_state9 = 12'd256;
parameter    ap_ST_fsm_state10 = 12'd512;
parameter    ap_ST_fsm_state11 = 12'd1024;
parameter    ap_ST_fsm_state12 = 12'd2048;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [0:0] user_id0;
input  [0:0] user_id1;
input  [15:0] temp1_re397_dout;
input   temp1_re397_empty_n;
output   temp1_re397_read;
input  [15:0] temp1_im398_dout;
input   temp1_im398_empty_n;
output   temp1_im398_read;
output  [15:0] temp2_re399_din;
input   temp2_re399_full_n;
output   temp2_re399_write;
output  [15:0] temp2_im400_din;
input   temp2_im400_full_n;
output   temp2_im400_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg temp1_re397_read;
reg temp1_im398_read;
reg temp2_re399_write;
reg temp2_im400_write;

(* fsm_encoding = "none" *) reg   [11:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [1:0] user_id_fu_219_p3;
reg   [1:0] user_id_reg_228;
wire    ap_CS_fsm_state3;
reg   [9:0] pilot_sym_M_real_V_address0;
reg    pilot_sym_M_real_V_ce0;
reg    pilot_sym_M_real_V_we0;
wire   [14:0] pilot_sym_M_real_V_q0;
reg    pilot_sym_M_real_V_ce1;
reg    pilot_sym_M_real_V_we1;
reg   [9:0] pilot_sym_M_imag_V_address0;
reg    pilot_sym_M_imag_V_ce0;
reg    pilot_sym_M_imag_V_we0;
wire   [14:0] pilot_sym_M_imag_V_q0;
reg    pilot_sym_M_imag_V_ce1;
reg    pilot_sym_M_imag_V_we1;
reg   [9:0] pilot_vle_M_real_V_address0;
reg    pilot_vle_M_real_V_ce0;
reg    pilot_vle_M_real_V_we0;
reg   [14:0] pilot_vle_M_real_V_d0;
wire   [14:0] pilot_vle_M_real_V_q0;
reg   [9:0] pilot_vle_M_imag_V_address0;
reg    pilot_vle_M_imag_V_ce0;
reg    pilot_vle_M_imag_V_we0;
reg   [14:0] pilot_vle_M_imag_V_d0;
wire   [14:0] pilot_vle_M_imag_V_q0;
reg   [9:0] data_symb1_M_real_V_address0;
reg    data_symb1_M_real_V_ce0;
reg    data_symb1_M_real_V_we0;
wire   [15:0] data_symb1_M_real_V_q0;
reg    data_symb1_M_real_V_ce1;
reg    data_symb1_M_real_V_we1;
reg   [9:0] data_symb1_M_imag_V_address0;
reg    data_symb1_M_imag_V_ce0;
reg    data_symb1_M_imag_V_we0;
wire   [15:0] data_symb1_M_imag_V_q0;
reg    data_symb1_M_imag_V_ce1;
reg    data_symb1_M_imag_V_we1;
reg   [9:0] data_symb2_M_real_V_address0;
reg    data_symb2_M_real_V_ce0;
reg    data_symb2_M_real_V_we0;
wire   [15:0] data_symb2_M_real_V_q0;
reg    data_symb2_M_real_V_ce1;
reg    data_symb2_M_real_V_we1;
reg   [9:0] data_symb2_M_imag_V_address0;
reg    data_symb2_M_imag_V_ce0;
reg    data_symb2_M_imag_V_we0;
wire   [15:0] data_symb2_M_imag_V_q0;
reg    data_symb2_M_imag_V_ce1;
reg    data_symb2_M_imag_V_we1;
reg   [9:0] symb1_M_real_V_address0;
reg    symb1_M_real_V_ce0;
reg    symb1_M_real_V_we0;
wire   [15:0] symb1_M_real_V_q0;
reg   [9:0] symb1_M_imag_V_address0;
reg    symb1_M_imag_V_ce0;
reg    symb1_M_imag_V_we0;
wire   [15:0] symb1_M_imag_V_q0;
reg   [9:0] symb2_M_real_V_address0;
reg    symb2_M_real_V_ce0;
reg    symb2_M_real_V_we0;
wire   [15:0] symb2_M_real_V_q0;
reg   [9:0] symb2_M_imag_V_address0;
reg    symb2_M_imag_V_ce0;
reg    symb2_M_imag_V_we0;
wire   [15:0] symb2_M_imag_V_q0;
wire    grp_adding_pilot_Pipeline_initial2_fu_116_ap_start;
wire    grp_adding_pilot_Pipeline_initial2_fu_116_ap_done;
wire    grp_adding_pilot_Pipeline_initial2_fu_116_ap_idle;
wire    grp_adding_pilot_Pipeline_initial2_fu_116_ap_ready;
wire   [9:0] grp_adding_pilot_Pipeline_initial2_fu_116_pilot_vle_M_real_V_address0;
wire    grp_adding_pilot_Pipeline_initial2_fu_116_pilot_vle_M_real_V_ce0;
wire    grp_adding_pilot_Pipeline_initial2_fu_116_pilot_vle_M_real_V_we0;
wire   [14:0] grp_adding_pilot_Pipeline_initial2_fu_116_pilot_vle_M_real_V_d0;
wire   [9:0] grp_adding_pilot_Pipeline_initial2_fu_116_pilot_vle_M_imag_V_address0;
wire    grp_adding_pilot_Pipeline_initial2_fu_116_pilot_vle_M_imag_V_ce0;
wire    grp_adding_pilot_Pipeline_initial2_fu_116_pilot_vle_M_imag_V_we0;
wire   [14:0] grp_adding_pilot_Pipeline_initial2_fu_116_pilot_vle_M_imag_V_d0;
wire    grp_adding_pilot_Pipeline_initil_upink_pilot_fu_124_ap_start;
wire    grp_adding_pilot_Pipeline_initil_upink_pilot_fu_124_ap_done;
wire    grp_adding_pilot_Pipeline_initil_upink_pilot_fu_124_ap_idle;
wire    grp_adding_pilot_Pipeline_initil_upink_pilot_fu_124_ap_ready;
wire   [9:0] grp_adding_pilot_Pipeline_initil_upink_pilot_fu_124_pilot_vle_M_real_V_address0;
wire    grp_adding_pilot_Pipeline_initil_upink_pilot_fu_124_pilot_vle_M_real_V_ce0;
wire    grp_adding_pilot_Pipeline_initil_upink_pilot_fu_124_pilot_vle_M_real_V_we0;
wire   [14:0] grp_adding_pilot_Pipeline_initil_upink_pilot_fu_124_pilot_vle_M_real_V_d0;
wire   [9:0] grp_adding_pilot_Pipeline_initil_upink_pilot_fu_124_pilot_vle_M_imag_V_address0;
wire    grp_adding_pilot_Pipeline_initil_upink_pilot_fu_124_pilot_vle_M_imag_V_ce0;
wire    grp_adding_pilot_Pipeline_initil_upink_pilot_fu_124_pilot_vle_M_imag_V_we0;
wire   [14:0] grp_adding_pilot_Pipeline_initil_upink_pilot_fu_124_pilot_vle_M_imag_V_d0;
wire    grp_adding_pilot_Pipeline_pilot_symb_fu_135_ap_start;
wire    grp_adding_pilot_Pipeline_pilot_symb_fu_135_ap_done;
wire    grp_adding_pilot_Pipeline_pilot_symb_fu_135_ap_idle;
wire    grp_adding_pilot_Pipeline_pilot_symb_fu_135_ap_ready;
wire   [9:0] grp_adding_pilot_Pipeline_pilot_symb_fu_135_pilot_sym_M_imag_V_address0;
wire    grp_adding_pilot_Pipeline_pilot_symb_fu_135_pilot_sym_M_imag_V_ce0;
wire    grp_adding_pilot_Pipeline_pilot_symb_fu_135_pilot_sym_M_imag_V_we0;
wire   [14:0] grp_adding_pilot_Pipeline_pilot_symb_fu_135_pilot_sym_M_imag_V_d0;
wire   [9:0] grp_adding_pilot_Pipeline_pilot_symb_fu_135_pilot_sym_M_imag_V_address1;
wire    grp_adding_pilot_Pipeline_pilot_symb_fu_135_pilot_sym_M_imag_V_ce1;
wire    grp_adding_pilot_Pipeline_pilot_symb_fu_135_pilot_sym_M_imag_V_we1;
wire   [14:0] grp_adding_pilot_Pipeline_pilot_symb_fu_135_pilot_sym_M_imag_V_d1;
wire   [9:0] grp_adding_pilot_Pipeline_pilot_symb_fu_135_pilot_sym_M_real_V_address0;
wire    grp_adding_pilot_Pipeline_pilot_symb_fu_135_pilot_sym_M_real_V_ce0;
wire    grp_adding_pilot_Pipeline_pilot_symb_fu_135_pilot_sym_M_real_V_we0;
wire   [14:0] grp_adding_pilot_Pipeline_pilot_symb_fu_135_pilot_sym_M_real_V_d0;
wire   [9:0] grp_adding_pilot_Pipeline_pilot_symb_fu_135_pilot_sym_M_real_V_address1;
wire    grp_adding_pilot_Pipeline_pilot_symb_fu_135_pilot_sym_M_real_V_ce1;
wire    grp_adding_pilot_Pipeline_pilot_symb_fu_135_pilot_sym_M_real_V_we1;
wire   [14:0] grp_adding_pilot_Pipeline_pilot_symb_fu_135_pilot_sym_M_real_V_d1;
wire   [9:0] grp_adding_pilot_Pipeline_pilot_symb_fu_135_pilot_vle_M_real_V_address0;
wire    grp_adding_pilot_Pipeline_pilot_symb_fu_135_pilot_vle_M_real_V_ce0;
wire   [9:0] grp_adding_pilot_Pipeline_pilot_symb_fu_135_pilot_vle_M_imag_V_address0;
wire    grp_adding_pilot_Pipeline_pilot_symb_fu_135_pilot_vle_M_imag_V_ce0;
wire    grp_adding_pilot_Pipeline_symb_fu_143_ap_start;
wire    grp_adding_pilot_Pipeline_symb_fu_143_ap_done;
wire    grp_adding_pilot_Pipeline_symb_fu_143_ap_idle;
wire    grp_adding_pilot_Pipeline_symb_fu_143_ap_ready;
wire    grp_adding_pilot_Pipeline_symb_fu_143_temp1_re397_read;
wire    grp_adding_pilot_Pipeline_symb_fu_143_temp1_im398_read;
wire   [9:0] grp_adding_pilot_Pipeline_symb_fu_143_symb1_M_real_V_address0;
wire    grp_adding_pilot_Pipeline_symb_fu_143_symb1_M_real_V_ce0;
wire    grp_adding_pilot_Pipeline_symb_fu_143_symb1_M_real_V_we0;
wire   [15:0] grp_adding_pilot_Pipeline_symb_fu_143_symb1_M_real_V_d0;
wire   [9:0] grp_adding_pilot_Pipeline_symb_fu_143_symb1_M_imag_V_address0;
wire    grp_adding_pilot_Pipeline_symb_fu_143_symb1_M_imag_V_ce0;
wire    grp_adding_pilot_Pipeline_symb_fu_143_symb1_M_imag_V_we0;
wire   [15:0] grp_adding_pilot_Pipeline_symb_fu_143_symb1_M_imag_V_d0;
wire   [9:0] grp_adding_pilot_Pipeline_symb_fu_143_symb2_M_real_V_address0;
wire    grp_adding_pilot_Pipeline_symb_fu_143_symb2_M_real_V_ce0;
wire    grp_adding_pilot_Pipeline_symb_fu_143_symb2_M_real_V_we0;
wire   [15:0] grp_adding_pilot_Pipeline_symb_fu_143_symb2_M_real_V_d0;
wire   [9:0] grp_adding_pilot_Pipeline_symb_fu_143_symb2_M_imag_V_address0;
wire    grp_adding_pilot_Pipeline_symb_fu_143_symb2_M_imag_V_ce0;
wire    grp_adding_pilot_Pipeline_symb_fu_143_symb2_M_imag_V_we0;
wire   [15:0] grp_adding_pilot_Pipeline_symb_fu_143_symb2_M_imag_V_d0;
wire    grp_adding_pilot_Pipeline_data_symbol_fu_155_ap_start;
wire    grp_adding_pilot_Pipeline_data_symbol_fu_155_ap_done;
wire    grp_adding_pilot_Pipeline_data_symbol_fu_155_ap_idle;
wire    grp_adding_pilot_Pipeline_data_symbol_fu_155_ap_ready;
wire   [9:0] grp_adding_pilot_Pipeline_data_symbol_fu_155_data_symb1_M_imag_V_address0;
wire    grp_adding_pilot_Pipeline_data_symbol_fu_155_data_symb1_M_imag_V_ce0;
wire    grp_adding_pilot_Pipeline_data_symbol_fu_155_data_symb1_M_imag_V_we0;
wire   [15:0] grp_adding_pilot_Pipeline_data_symbol_fu_155_data_symb1_M_imag_V_d0;
wire   [9:0] grp_adding_pilot_Pipeline_data_symbol_fu_155_data_symb1_M_imag_V_address1;
wire    grp_adding_pilot_Pipeline_data_symbol_fu_155_data_symb1_M_imag_V_ce1;
wire    grp_adding_pilot_Pipeline_data_symbol_fu_155_data_symb1_M_imag_V_we1;
wire   [15:0] grp_adding_pilot_Pipeline_data_symbol_fu_155_data_symb1_M_imag_V_d1;
wire   [9:0] grp_adding_pilot_Pipeline_data_symbol_fu_155_data_symb1_M_real_V_address0;
wire    grp_adding_pilot_Pipeline_data_symbol_fu_155_data_symb1_M_real_V_ce0;
wire    grp_adding_pilot_Pipeline_data_symbol_fu_155_data_symb1_M_real_V_we0;
wire   [15:0] grp_adding_pilot_Pipeline_data_symbol_fu_155_data_symb1_M_real_V_d0;
wire   [9:0] grp_adding_pilot_Pipeline_data_symbol_fu_155_data_symb1_M_real_V_address1;
wire    grp_adding_pilot_Pipeline_data_symbol_fu_155_data_symb1_M_real_V_ce1;
wire    grp_adding_pilot_Pipeline_data_symbol_fu_155_data_symb1_M_real_V_we1;
wire   [15:0] grp_adding_pilot_Pipeline_data_symbol_fu_155_data_symb1_M_real_V_d1;
wire   [9:0] grp_adding_pilot_Pipeline_data_symbol_fu_155_symb1_M_real_V_address0;
wire    grp_adding_pilot_Pipeline_data_symbol_fu_155_symb1_M_real_V_ce0;
wire   [9:0] grp_adding_pilot_Pipeline_data_symbol_fu_155_symb1_M_imag_V_address0;
wire    grp_adding_pilot_Pipeline_data_symbol_fu_155_symb1_M_imag_V_ce0;
wire    grp_adding_pilot_Pipeline_data_symbo2_fu_163_ap_start;
wire    grp_adding_pilot_Pipeline_data_symbo2_fu_163_ap_done;
wire    grp_adding_pilot_Pipeline_data_symbo2_fu_163_ap_idle;
wire    grp_adding_pilot_Pipeline_data_symbo2_fu_163_ap_ready;
wire   [9:0] grp_adding_pilot_Pipeline_data_symbo2_fu_163_data_symb2_M_imag_V_address0;
wire    grp_adding_pilot_Pipeline_data_symbo2_fu_163_data_symb2_M_imag_V_ce0;
wire    grp_adding_pilot_Pipeline_data_symbo2_fu_163_data_symb2_M_imag_V_we0;
wire   [15:0] grp_adding_pilot_Pipeline_data_symbo2_fu_163_data_symb2_M_imag_V_d0;
wire   [9:0] grp_adding_pilot_Pipeline_data_symbo2_fu_163_data_symb2_M_imag_V_address1;
wire    grp_adding_pilot_Pipeline_data_symbo2_fu_163_data_symb2_M_imag_V_ce1;
wire    grp_adding_pilot_Pipeline_data_symbo2_fu_163_data_symb2_M_imag_V_we1;
wire   [15:0] grp_adding_pilot_Pipeline_data_symbo2_fu_163_data_symb2_M_imag_V_d1;
wire   [9:0] grp_adding_pilot_Pipeline_data_symbo2_fu_163_data_symb2_M_real_V_address0;
wire    grp_adding_pilot_Pipeline_data_symbo2_fu_163_data_symb2_M_real_V_ce0;
wire    grp_adding_pilot_Pipeline_data_symbo2_fu_163_data_symb2_M_real_V_we0;
wire   [15:0] grp_adding_pilot_Pipeline_data_symbo2_fu_163_data_symb2_M_real_V_d0;
wire   [9:0] grp_adding_pilot_Pipeline_data_symbo2_fu_163_data_symb2_M_real_V_address1;
wire    grp_adding_pilot_Pipeline_data_symbo2_fu_163_data_symb2_M_real_V_ce1;
wire    grp_adding_pilot_Pipeline_data_symbo2_fu_163_data_symb2_M_real_V_we1;
wire   [15:0] grp_adding_pilot_Pipeline_data_symbo2_fu_163_data_symb2_M_real_V_d1;
wire   [9:0] grp_adding_pilot_Pipeline_data_symbo2_fu_163_symb2_M_real_V_address0;
wire    grp_adding_pilot_Pipeline_data_symbo2_fu_163_symb2_M_real_V_ce0;
wire   [9:0] grp_adding_pilot_Pipeline_data_symbo2_fu_163_symb2_M_imag_V_address0;
wire    grp_adding_pilot_Pipeline_data_symbo2_fu_163_symb2_M_imag_V_ce0;
wire    grp_adding_pilot_Pipeline_output_arrangement_fu_171_ap_start;
wire    grp_adding_pilot_Pipeline_output_arrangement_fu_171_ap_done;
wire    grp_adding_pilot_Pipeline_output_arrangement_fu_171_ap_idle;
wire    grp_adding_pilot_Pipeline_output_arrangement_fu_171_ap_ready;
wire   [15:0] grp_adding_pilot_Pipeline_output_arrangement_fu_171_temp2_re399_din;
wire    grp_adding_pilot_Pipeline_output_arrangement_fu_171_temp2_re399_write;
wire   [15:0] grp_adding_pilot_Pipeline_output_arrangement_fu_171_temp2_im400_din;
wire    grp_adding_pilot_Pipeline_output_arrangement_fu_171_temp2_im400_write;
wire   [9:0] grp_adding_pilot_Pipeline_output_arrangement_fu_171_pilot_sym_M_real_V_address0;
wire    grp_adding_pilot_Pipeline_output_arrangement_fu_171_pilot_sym_M_real_V_ce0;
wire   [9:0] grp_adding_pilot_Pipeline_output_arrangement_fu_171_pilot_sym_M_imag_V_address0;
wire    grp_adding_pilot_Pipeline_output_arrangement_fu_171_pilot_sym_M_imag_V_ce0;
wire   [9:0] grp_adding_pilot_Pipeline_output_arrangement_fu_171_data_symb1_M_real_V_address0;
wire    grp_adding_pilot_Pipeline_output_arrangement_fu_171_data_symb1_M_real_V_ce0;
wire   [9:0] grp_adding_pilot_Pipeline_output_arrangement_fu_171_data_symb1_M_imag_V_address0;
wire    grp_adding_pilot_Pipeline_output_arrangement_fu_171_data_symb1_M_imag_V_ce0;
wire   [9:0] grp_adding_pilot_Pipeline_output_arrangement_fu_171_data_symb2_M_real_V_address0;
wire    grp_adding_pilot_Pipeline_output_arrangement_fu_171_data_symb2_M_real_V_ce0;
wire   [9:0] grp_adding_pilot_Pipeline_output_arrangement_fu_171_data_symb2_M_imag_V_address0;
wire    grp_adding_pilot_Pipeline_output_arrangement_fu_171_data_symb2_M_imag_V_ce0;
reg    grp_adding_pilot_Pipeline_initial2_fu_116_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_adding_pilot_Pipeline_initil_upink_pilot_fu_124_ap_start_reg;
wire    ap_CS_fsm_state4;
reg    grp_adding_pilot_Pipeline_pilot_symb_fu_135_ap_start_reg;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
reg    grp_adding_pilot_Pipeline_symb_fu_143_ap_start_reg;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
reg    grp_adding_pilot_Pipeline_data_symbol_fu_155_ap_start_reg;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state10;
reg    grp_adding_pilot_Pipeline_data_symbo2_fu_163_ap_start_reg;
reg    grp_adding_pilot_Pipeline_output_arrangement_fu_171_ap_start_reg;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state12;
wire   [0:0] xor_ln27_fu_185_p2;
wire   [0:0] and_ln35_fu_197_p2;
wire   [1:0] select_ln35_fu_203_p3;
wire   [0:0] or_ln27_fu_191_p2;
wire   [1:0] select_ln31_fu_211_p3;
reg   [11:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_block_state10_on_subcall_done;
reg    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
reg    ap_ST_fsm_state12_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 12'd1;
#0 grp_adding_pilot_Pipeline_initial2_fu_116_ap_start_reg = 1'b0;
#0 grp_adding_pilot_Pipeline_initil_upink_pilot_fu_124_ap_start_reg = 1'b0;
#0 grp_adding_pilot_Pipeline_pilot_symb_fu_135_ap_start_reg = 1'b0;
#0 grp_adding_pilot_Pipeline_symb_fu_143_ap_start_reg = 1'b0;
#0 grp_adding_pilot_Pipeline_data_symbol_fu_155_ap_start_reg = 1'b0;
#0 grp_adding_pilot_Pipeline_data_symbo2_fu_163_ap_start_reg = 1'b0;
#0 grp_adding_pilot_Pipeline_output_arrangement_fu_171_ap_start_reg = 1'b0;
end

top_tx_adding_pilot_pilot_sym_M_real_V_RAM_AUTO_1R1W #(
    .DataWidth( 15 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
pilot_sym_M_real_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(pilot_sym_M_real_V_address0),
    .ce0(pilot_sym_M_real_V_ce0),
    .we0(pilot_sym_M_real_V_we0),
    .d0(grp_adding_pilot_Pipeline_pilot_symb_fu_135_pilot_sym_M_real_V_d0),
    .q0(pilot_sym_M_real_V_q0),
    .address1(grp_adding_pilot_Pipeline_pilot_symb_fu_135_pilot_sym_M_real_V_address1),
    .ce1(pilot_sym_M_real_V_ce1),
    .we1(pilot_sym_M_real_V_we1),
    .d1(grp_adding_pilot_Pipeline_pilot_symb_fu_135_pilot_sym_M_real_V_d1)
);

top_tx_adding_pilot_pilot_sym_M_real_V_RAM_AUTO_1R1W #(
    .DataWidth( 15 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
pilot_sym_M_imag_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(pilot_sym_M_imag_V_address0),
    .ce0(pilot_sym_M_imag_V_ce0),
    .we0(pilot_sym_M_imag_V_we0),
    .d0(grp_adding_pilot_Pipeline_pilot_symb_fu_135_pilot_sym_M_imag_V_d0),
    .q0(pilot_sym_M_imag_V_q0),
    .address1(grp_adding_pilot_Pipeline_pilot_symb_fu_135_pilot_sym_M_imag_V_address1),
    .ce1(pilot_sym_M_imag_V_ce1),
    .we1(pilot_sym_M_imag_V_we1),
    .d1(grp_adding_pilot_Pipeline_pilot_symb_fu_135_pilot_sym_M_imag_V_d1)
);

top_tx_adding_pilot_pilot_vle_M_real_V_RAM_AUTO_1R1W #(
    .DataWidth( 15 ),
    .AddressRange( 600 ),
    .AddressWidth( 10 ))
pilot_vle_M_real_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(pilot_vle_M_real_V_address0),
    .ce0(pilot_vle_M_real_V_ce0),
    .we0(pilot_vle_M_real_V_we0),
    .d0(pilot_vle_M_real_V_d0),
    .q0(pilot_vle_M_real_V_q0)
);

top_tx_adding_pilot_pilot_vle_M_real_V_RAM_AUTO_1R1W #(
    .DataWidth( 15 ),
    .AddressRange( 600 ),
    .AddressWidth( 10 ))
pilot_vle_M_imag_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(pilot_vle_M_imag_V_address0),
    .ce0(pilot_vle_M_imag_V_ce0),
    .we0(pilot_vle_M_imag_V_we0),
    .d0(pilot_vle_M_imag_V_d0),
    .q0(pilot_vle_M_imag_V_q0)
);

top_tx_adding_pilot_data_symb1_M_real_V_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
data_symb1_M_real_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(data_symb1_M_real_V_address0),
    .ce0(data_symb1_M_real_V_ce0),
    .we0(data_symb1_M_real_V_we0),
    .d0(grp_adding_pilot_Pipeline_data_symbol_fu_155_data_symb1_M_real_V_d0),
    .q0(data_symb1_M_real_V_q0),
    .address1(grp_adding_pilot_Pipeline_data_symbol_fu_155_data_symb1_M_real_V_address1),
    .ce1(data_symb1_M_real_V_ce1),
    .we1(data_symb1_M_real_V_we1),
    .d1(grp_adding_pilot_Pipeline_data_symbol_fu_155_data_symb1_M_real_V_d1)
);

top_tx_adding_pilot_data_symb1_M_real_V_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
data_symb1_M_imag_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(data_symb1_M_imag_V_address0),
    .ce0(data_symb1_M_imag_V_ce0),
    .we0(data_symb1_M_imag_V_we0),
    .d0(grp_adding_pilot_Pipeline_data_symbol_fu_155_data_symb1_M_imag_V_d0),
    .q0(data_symb1_M_imag_V_q0),
    .address1(grp_adding_pilot_Pipeline_data_symbol_fu_155_data_symb1_M_imag_V_address1),
    .ce1(data_symb1_M_imag_V_ce1),
    .we1(data_symb1_M_imag_V_we1),
    .d1(grp_adding_pilot_Pipeline_data_symbol_fu_155_data_symb1_M_imag_V_d1)
);

top_tx_adding_pilot_data_symb1_M_real_V_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
data_symb2_M_real_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(data_symb2_M_real_V_address0),
    .ce0(data_symb2_M_real_V_ce0),
    .we0(data_symb2_M_real_V_we0),
    .d0(grp_adding_pilot_Pipeline_data_symbo2_fu_163_data_symb2_M_real_V_d0),
    .q0(data_symb2_M_real_V_q0),
    .address1(grp_adding_pilot_Pipeline_data_symbo2_fu_163_data_symb2_M_real_V_address1),
    .ce1(data_symb2_M_real_V_ce1),
    .we1(data_symb2_M_real_V_we1),
    .d1(grp_adding_pilot_Pipeline_data_symbo2_fu_163_data_symb2_M_real_V_d1)
);

top_tx_adding_pilot_data_symb1_M_real_V_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
data_symb2_M_imag_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(data_symb2_M_imag_V_address0),
    .ce0(data_symb2_M_imag_V_ce0),
    .we0(data_symb2_M_imag_V_we0),
    .d0(grp_adding_pilot_Pipeline_data_symbo2_fu_163_data_symb2_M_imag_V_d0),
    .q0(data_symb2_M_imag_V_q0),
    .address1(grp_adding_pilot_Pipeline_data_symbo2_fu_163_data_symb2_M_imag_V_address1),
    .ce1(data_symb2_M_imag_V_ce1),
    .we1(data_symb2_M_imag_V_we1),
    .d1(grp_adding_pilot_Pipeline_data_symbo2_fu_163_data_symb2_M_imag_V_d1)
);

top_tx_adding_pilot_symb1_M_real_V_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 600 ),
    .AddressWidth( 10 ))
symb1_M_real_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(symb1_M_real_V_address0),
    .ce0(symb1_M_real_V_ce0),
    .we0(symb1_M_real_V_we0),
    .d0(grp_adding_pilot_Pipeline_symb_fu_143_symb1_M_real_V_d0),
    .q0(symb1_M_real_V_q0)
);

top_tx_adding_pilot_symb1_M_real_V_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 600 ),
    .AddressWidth( 10 ))
symb1_M_imag_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(symb1_M_imag_V_address0),
    .ce0(symb1_M_imag_V_ce0),
    .we0(symb1_M_imag_V_we0),
    .d0(grp_adding_pilot_Pipeline_symb_fu_143_symb1_M_imag_V_d0),
    .q0(symb1_M_imag_V_q0)
);

top_tx_adding_pilot_symb1_M_real_V_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 600 ),
    .AddressWidth( 10 ))
symb2_M_real_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(symb2_M_real_V_address0),
    .ce0(symb2_M_real_V_ce0),
    .we0(symb2_M_real_V_we0),
    .d0(grp_adding_pilot_Pipeline_symb_fu_143_symb2_M_real_V_d0),
    .q0(symb2_M_real_V_q0)
);

top_tx_adding_pilot_symb1_M_real_V_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 600 ),
    .AddressWidth( 10 ))
symb2_M_imag_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(symb2_M_imag_V_address0),
    .ce0(symb2_M_imag_V_ce0),
    .we0(symb2_M_imag_V_we0),
    .d0(grp_adding_pilot_Pipeline_symb_fu_143_symb2_M_imag_V_d0),
    .q0(symb2_M_imag_V_q0)
);

top_tx_adding_pilot_Pipeline_initial2 grp_adding_pilot_Pipeline_initial2_fu_116(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_adding_pilot_Pipeline_initial2_fu_116_ap_start),
    .ap_done(grp_adding_pilot_Pipeline_initial2_fu_116_ap_done),
    .ap_idle(grp_adding_pilot_Pipeline_initial2_fu_116_ap_idle),
    .ap_ready(grp_adding_pilot_Pipeline_initial2_fu_116_ap_ready),
    .pilot_vle_M_real_V_address0(grp_adding_pilot_Pipeline_initial2_fu_116_pilot_vle_M_real_V_address0),
    .pilot_vle_M_real_V_ce0(grp_adding_pilot_Pipeline_initial2_fu_116_pilot_vle_M_real_V_ce0),
    .pilot_vle_M_real_V_we0(grp_adding_pilot_Pipeline_initial2_fu_116_pilot_vle_M_real_V_we0),
    .pilot_vle_M_real_V_d0(grp_adding_pilot_Pipeline_initial2_fu_116_pilot_vle_M_real_V_d0),
    .pilot_vle_M_imag_V_address0(grp_adding_pilot_Pipeline_initial2_fu_116_pilot_vle_M_imag_V_address0),
    .pilot_vle_M_imag_V_ce0(grp_adding_pilot_Pipeline_initial2_fu_116_pilot_vle_M_imag_V_ce0),
    .pilot_vle_M_imag_V_we0(grp_adding_pilot_Pipeline_initial2_fu_116_pilot_vle_M_imag_V_we0),
    .pilot_vle_M_imag_V_d0(grp_adding_pilot_Pipeline_initial2_fu_116_pilot_vle_M_imag_V_d0)
);

top_tx_adding_pilot_Pipeline_initil_upink_pilot grp_adding_pilot_Pipeline_initil_upink_pilot_fu_124(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_adding_pilot_Pipeline_initil_upink_pilot_fu_124_ap_start),
    .ap_done(grp_adding_pilot_Pipeline_initil_upink_pilot_fu_124_ap_done),
    .ap_idle(grp_adding_pilot_Pipeline_initil_upink_pilot_fu_124_ap_idle),
    .ap_ready(grp_adding_pilot_Pipeline_initil_upink_pilot_fu_124_ap_ready),
    .zext_ln46(user_id_reg_228),
    .pilot_vle_M_real_V_address0(grp_adding_pilot_Pipeline_initil_upink_pilot_fu_124_pilot_vle_M_real_V_address0),
    .pilot_vle_M_real_V_ce0(grp_adding_pilot_Pipeline_initil_upink_pilot_fu_124_pilot_vle_M_real_V_ce0),
    .pilot_vle_M_real_V_we0(grp_adding_pilot_Pipeline_initil_upink_pilot_fu_124_pilot_vle_M_real_V_we0),
    .pilot_vle_M_real_V_d0(grp_adding_pilot_Pipeline_initil_upink_pilot_fu_124_pilot_vle_M_real_V_d0),
    .pilot_vle_M_imag_V_address0(grp_adding_pilot_Pipeline_initil_upink_pilot_fu_124_pilot_vle_M_imag_V_address0),
    .pilot_vle_M_imag_V_ce0(grp_adding_pilot_Pipeline_initil_upink_pilot_fu_124_pilot_vle_M_imag_V_ce0),
    .pilot_vle_M_imag_V_we0(grp_adding_pilot_Pipeline_initil_upink_pilot_fu_124_pilot_vle_M_imag_V_we0),
    .pilot_vle_M_imag_V_d0(grp_adding_pilot_Pipeline_initil_upink_pilot_fu_124_pilot_vle_M_imag_V_d0)
);

top_tx_adding_pilot_Pipeline_pilot_symb grp_adding_pilot_Pipeline_pilot_symb_fu_135(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_adding_pilot_Pipeline_pilot_symb_fu_135_ap_start),
    .ap_done(grp_adding_pilot_Pipeline_pilot_symb_fu_135_ap_done),
    .ap_idle(grp_adding_pilot_Pipeline_pilot_symb_fu_135_ap_idle),
    .ap_ready(grp_adding_pilot_Pipeline_pilot_symb_fu_135_ap_ready),
    .pilot_sym_M_imag_V_address0(grp_adding_pilot_Pipeline_pilot_symb_fu_135_pilot_sym_M_imag_V_address0),
    .pilot_sym_M_imag_V_ce0(grp_adding_pilot_Pipeline_pilot_symb_fu_135_pilot_sym_M_imag_V_ce0),
    .pilot_sym_M_imag_V_we0(grp_adding_pilot_Pipeline_pilot_symb_fu_135_pilot_sym_M_imag_V_we0),
    .pilot_sym_M_imag_V_d0(grp_adding_pilot_Pipeline_pilot_symb_fu_135_pilot_sym_M_imag_V_d0),
    .pilot_sym_M_imag_V_address1(grp_adding_pilot_Pipeline_pilot_symb_fu_135_pilot_sym_M_imag_V_address1),
    .pilot_sym_M_imag_V_ce1(grp_adding_pilot_Pipeline_pilot_symb_fu_135_pilot_sym_M_imag_V_ce1),
    .pilot_sym_M_imag_V_we1(grp_adding_pilot_Pipeline_pilot_symb_fu_135_pilot_sym_M_imag_V_we1),
    .pilot_sym_M_imag_V_d1(grp_adding_pilot_Pipeline_pilot_symb_fu_135_pilot_sym_M_imag_V_d1),
    .pilot_sym_M_real_V_address0(grp_adding_pilot_Pipeline_pilot_symb_fu_135_pilot_sym_M_real_V_address0),
    .pilot_sym_M_real_V_ce0(grp_adding_pilot_Pipeline_pilot_symb_fu_135_pilot_sym_M_real_V_ce0),
    .pilot_sym_M_real_V_we0(grp_adding_pilot_Pipeline_pilot_symb_fu_135_pilot_sym_M_real_V_we0),
    .pilot_sym_M_real_V_d0(grp_adding_pilot_Pipeline_pilot_symb_fu_135_pilot_sym_M_real_V_d0),
    .pilot_sym_M_real_V_address1(grp_adding_pilot_Pipeline_pilot_symb_fu_135_pilot_sym_M_real_V_address1),
    .pilot_sym_M_real_V_ce1(grp_adding_pilot_Pipeline_pilot_symb_fu_135_pilot_sym_M_real_V_ce1),
    .pilot_sym_M_real_V_we1(grp_adding_pilot_Pipeline_pilot_symb_fu_135_pilot_sym_M_real_V_we1),
    .pilot_sym_M_real_V_d1(grp_adding_pilot_Pipeline_pilot_symb_fu_135_pilot_sym_M_real_V_d1),
    .pilot_vle_M_real_V_address0(grp_adding_pilot_Pipeline_pilot_symb_fu_135_pilot_vle_M_real_V_address0),
    .pilot_vle_M_real_V_ce0(grp_adding_pilot_Pipeline_pilot_symb_fu_135_pilot_vle_M_real_V_ce0),
    .pilot_vle_M_real_V_q0(pilot_vle_M_real_V_q0),
    .pilot_vle_M_imag_V_address0(grp_adding_pilot_Pipeline_pilot_symb_fu_135_pilot_vle_M_imag_V_address0),
    .pilot_vle_M_imag_V_ce0(grp_adding_pilot_Pipeline_pilot_symb_fu_135_pilot_vle_M_imag_V_ce0),
    .pilot_vle_M_imag_V_q0(pilot_vle_M_imag_V_q0)
);

top_tx_adding_pilot_Pipeline_symb grp_adding_pilot_Pipeline_symb_fu_143(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_adding_pilot_Pipeline_symb_fu_143_ap_start),
    .ap_done(grp_adding_pilot_Pipeline_symb_fu_143_ap_done),
    .ap_idle(grp_adding_pilot_Pipeline_symb_fu_143_ap_idle),
    .ap_ready(grp_adding_pilot_Pipeline_symb_fu_143_ap_ready),
    .temp1_re397_dout(temp1_re397_dout),
    .temp1_re397_empty_n(temp1_re397_empty_n),
    .temp1_re397_read(grp_adding_pilot_Pipeline_symb_fu_143_temp1_re397_read),
    .temp1_im398_dout(temp1_im398_dout),
    .temp1_im398_empty_n(temp1_im398_empty_n),
    .temp1_im398_read(grp_adding_pilot_Pipeline_symb_fu_143_temp1_im398_read),
    .symb1_M_real_V_address0(grp_adding_pilot_Pipeline_symb_fu_143_symb1_M_real_V_address0),
    .symb1_M_real_V_ce0(grp_adding_pilot_Pipeline_symb_fu_143_symb1_M_real_V_ce0),
    .symb1_M_real_V_we0(grp_adding_pilot_Pipeline_symb_fu_143_symb1_M_real_V_we0),
    .symb1_M_real_V_d0(grp_adding_pilot_Pipeline_symb_fu_143_symb1_M_real_V_d0),
    .symb1_M_imag_V_address0(grp_adding_pilot_Pipeline_symb_fu_143_symb1_M_imag_V_address0),
    .symb1_M_imag_V_ce0(grp_adding_pilot_Pipeline_symb_fu_143_symb1_M_imag_V_ce0),
    .symb1_M_imag_V_we0(grp_adding_pilot_Pipeline_symb_fu_143_symb1_M_imag_V_we0),
    .symb1_M_imag_V_d0(grp_adding_pilot_Pipeline_symb_fu_143_symb1_M_imag_V_d0),
    .symb2_M_real_V_address0(grp_adding_pilot_Pipeline_symb_fu_143_symb2_M_real_V_address0),
    .symb2_M_real_V_ce0(grp_adding_pilot_Pipeline_symb_fu_143_symb2_M_real_V_ce0),
    .symb2_M_real_V_we0(grp_adding_pilot_Pipeline_symb_fu_143_symb2_M_real_V_we0),
    .symb2_M_real_V_d0(grp_adding_pilot_Pipeline_symb_fu_143_symb2_M_real_V_d0),
    .symb2_M_imag_V_address0(grp_adding_pilot_Pipeline_symb_fu_143_symb2_M_imag_V_address0),
    .symb2_M_imag_V_ce0(grp_adding_pilot_Pipeline_symb_fu_143_symb2_M_imag_V_ce0),
    .symb2_M_imag_V_we0(grp_adding_pilot_Pipeline_symb_fu_143_symb2_M_imag_V_we0),
    .symb2_M_imag_V_d0(grp_adding_pilot_Pipeline_symb_fu_143_symb2_M_imag_V_d0)
);

top_tx_adding_pilot_Pipeline_data_symbol grp_adding_pilot_Pipeline_data_symbol_fu_155(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_adding_pilot_Pipeline_data_symbol_fu_155_ap_start),
    .ap_done(grp_adding_pilot_Pipeline_data_symbol_fu_155_ap_done),
    .ap_idle(grp_adding_pilot_Pipeline_data_symbol_fu_155_ap_idle),
    .ap_ready(grp_adding_pilot_Pipeline_data_symbol_fu_155_ap_ready),
    .data_symb1_M_imag_V_address0(grp_adding_pilot_Pipeline_data_symbol_fu_155_data_symb1_M_imag_V_address0),
    .data_symb1_M_imag_V_ce0(grp_adding_pilot_Pipeline_data_symbol_fu_155_data_symb1_M_imag_V_ce0),
    .data_symb1_M_imag_V_we0(grp_adding_pilot_Pipeline_data_symbol_fu_155_data_symb1_M_imag_V_we0),
    .data_symb1_M_imag_V_d0(grp_adding_pilot_Pipeline_data_symbol_fu_155_data_symb1_M_imag_V_d0),
    .data_symb1_M_imag_V_address1(grp_adding_pilot_Pipeline_data_symbol_fu_155_data_symb1_M_imag_V_address1),
    .data_symb1_M_imag_V_ce1(grp_adding_pilot_Pipeline_data_symbol_fu_155_data_symb1_M_imag_V_ce1),
    .data_symb1_M_imag_V_we1(grp_adding_pilot_Pipeline_data_symbol_fu_155_data_symb1_M_imag_V_we1),
    .data_symb1_M_imag_V_d1(grp_adding_pilot_Pipeline_data_symbol_fu_155_data_symb1_M_imag_V_d1),
    .data_symb1_M_real_V_address0(grp_adding_pilot_Pipeline_data_symbol_fu_155_data_symb1_M_real_V_address0),
    .data_symb1_M_real_V_ce0(grp_adding_pilot_Pipeline_data_symbol_fu_155_data_symb1_M_real_V_ce0),
    .data_symb1_M_real_V_we0(grp_adding_pilot_Pipeline_data_symbol_fu_155_data_symb1_M_real_V_we0),
    .data_symb1_M_real_V_d0(grp_adding_pilot_Pipeline_data_symbol_fu_155_data_symb1_M_real_V_d0),
    .data_symb1_M_real_V_address1(grp_adding_pilot_Pipeline_data_symbol_fu_155_data_symb1_M_real_V_address1),
    .data_symb1_M_real_V_ce1(grp_adding_pilot_Pipeline_data_symbol_fu_155_data_symb1_M_real_V_ce1),
    .data_symb1_M_real_V_we1(grp_adding_pilot_Pipeline_data_symbol_fu_155_data_symb1_M_real_V_we1),
    .data_symb1_M_real_V_d1(grp_adding_pilot_Pipeline_data_symbol_fu_155_data_symb1_M_real_V_d1),
    .symb1_M_real_V_address0(grp_adding_pilot_Pipeline_data_symbol_fu_155_symb1_M_real_V_address0),
    .symb1_M_real_V_ce0(grp_adding_pilot_Pipeline_data_symbol_fu_155_symb1_M_real_V_ce0),
    .symb1_M_real_V_q0(symb1_M_real_V_q0),
    .symb1_M_imag_V_address0(grp_adding_pilot_Pipeline_data_symbol_fu_155_symb1_M_imag_V_address0),
    .symb1_M_imag_V_ce0(grp_adding_pilot_Pipeline_data_symbol_fu_155_symb1_M_imag_V_ce0),
    .symb1_M_imag_V_q0(symb1_M_imag_V_q0)
);

top_tx_adding_pilot_Pipeline_data_symbo2 grp_adding_pilot_Pipeline_data_symbo2_fu_163(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_adding_pilot_Pipeline_data_symbo2_fu_163_ap_start),
    .ap_done(grp_adding_pilot_Pipeline_data_symbo2_fu_163_ap_done),
    .ap_idle(grp_adding_pilot_Pipeline_data_symbo2_fu_163_ap_idle),
    .ap_ready(grp_adding_pilot_Pipeline_data_symbo2_fu_163_ap_ready),
    .data_symb2_M_imag_V_address0(grp_adding_pilot_Pipeline_data_symbo2_fu_163_data_symb2_M_imag_V_address0),
    .data_symb2_M_imag_V_ce0(grp_adding_pilot_Pipeline_data_symbo2_fu_163_data_symb2_M_imag_V_ce0),
    .data_symb2_M_imag_V_we0(grp_adding_pilot_Pipeline_data_symbo2_fu_163_data_symb2_M_imag_V_we0),
    .data_symb2_M_imag_V_d0(grp_adding_pilot_Pipeline_data_symbo2_fu_163_data_symb2_M_imag_V_d0),
    .data_symb2_M_imag_V_address1(grp_adding_pilot_Pipeline_data_symbo2_fu_163_data_symb2_M_imag_V_address1),
    .data_symb2_M_imag_V_ce1(grp_adding_pilot_Pipeline_data_symbo2_fu_163_data_symb2_M_imag_V_ce1),
    .data_symb2_M_imag_V_we1(grp_adding_pilot_Pipeline_data_symbo2_fu_163_data_symb2_M_imag_V_we1),
    .data_symb2_M_imag_V_d1(grp_adding_pilot_Pipeline_data_symbo2_fu_163_data_symb2_M_imag_V_d1),
    .data_symb2_M_real_V_address0(grp_adding_pilot_Pipeline_data_symbo2_fu_163_data_symb2_M_real_V_address0),
    .data_symb2_M_real_V_ce0(grp_adding_pilot_Pipeline_data_symbo2_fu_163_data_symb2_M_real_V_ce0),
    .data_symb2_M_real_V_we0(grp_adding_pilot_Pipeline_data_symbo2_fu_163_data_symb2_M_real_V_we0),
    .data_symb2_M_real_V_d0(grp_adding_pilot_Pipeline_data_symbo2_fu_163_data_symb2_M_real_V_d0),
    .data_symb2_M_real_V_address1(grp_adding_pilot_Pipeline_data_symbo2_fu_163_data_symb2_M_real_V_address1),
    .data_symb2_M_real_V_ce1(grp_adding_pilot_Pipeline_data_symbo2_fu_163_data_symb2_M_real_V_ce1),
    .data_symb2_M_real_V_we1(grp_adding_pilot_Pipeline_data_symbo2_fu_163_data_symb2_M_real_V_we1),
    .data_symb2_M_real_V_d1(grp_adding_pilot_Pipeline_data_symbo2_fu_163_data_symb2_M_real_V_d1),
    .symb2_M_real_V_address0(grp_adding_pilot_Pipeline_data_symbo2_fu_163_symb2_M_real_V_address0),
    .symb2_M_real_V_ce0(grp_adding_pilot_Pipeline_data_symbo2_fu_163_symb2_M_real_V_ce0),
    .symb2_M_real_V_q0(symb2_M_real_V_q0),
    .symb2_M_imag_V_address0(grp_adding_pilot_Pipeline_data_symbo2_fu_163_symb2_M_imag_V_address0),
    .symb2_M_imag_V_ce0(grp_adding_pilot_Pipeline_data_symbo2_fu_163_symb2_M_imag_V_ce0),
    .symb2_M_imag_V_q0(symb2_M_imag_V_q0)
);

top_tx_adding_pilot_Pipeline_output_arrangement grp_adding_pilot_Pipeline_output_arrangement_fu_171(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_adding_pilot_Pipeline_output_arrangement_fu_171_ap_start),
    .ap_done(grp_adding_pilot_Pipeline_output_arrangement_fu_171_ap_done),
    .ap_idle(grp_adding_pilot_Pipeline_output_arrangement_fu_171_ap_idle),
    .ap_ready(grp_adding_pilot_Pipeline_output_arrangement_fu_171_ap_ready),
    .temp2_re399_din(grp_adding_pilot_Pipeline_output_arrangement_fu_171_temp2_re399_din),
    .temp2_re399_full_n(temp2_re399_full_n),
    .temp2_re399_write(grp_adding_pilot_Pipeline_output_arrangement_fu_171_temp2_re399_write),
    .temp2_im400_din(grp_adding_pilot_Pipeline_output_arrangement_fu_171_temp2_im400_din),
    .temp2_im400_full_n(temp2_im400_full_n),
    .temp2_im400_write(grp_adding_pilot_Pipeline_output_arrangement_fu_171_temp2_im400_write),
    .pilot_sym_M_real_V_address0(grp_adding_pilot_Pipeline_output_arrangement_fu_171_pilot_sym_M_real_V_address0),
    .pilot_sym_M_real_V_ce0(grp_adding_pilot_Pipeline_output_arrangement_fu_171_pilot_sym_M_real_V_ce0),
    .pilot_sym_M_real_V_q0(pilot_sym_M_real_V_q0),
    .pilot_sym_M_imag_V_address0(grp_adding_pilot_Pipeline_output_arrangement_fu_171_pilot_sym_M_imag_V_address0),
    .pilot_sym_M_imag_V_ce0(grp_adding_pilot_Pipeline_output_arrangement_fu_171_pilot_sym_M_imag_V_ce0),
    .pilot_sym_M_imag_V_q0(pilot_sym_M_imag_V_q0),
    .data_symb1_M_real_V_address0(grp_adding_pilot_Pipeline_output_arrangement_fu_171_data_symb1_M_real_V_address0),
    .data_symb1_M_real_V_ce0(grp_adding_pilot_Pipeline_output_arrangement_fu_171_data_symb1_M_real_V_ce0),
    .data_symb1_M_real_V_q0(data_symb1_M_real_V_q0),
    .data_symb1_M_imag_V_address0(grp_adding_pilot_Pipeline_output_arrangement_fu_171_data_symb1_M_imag_V_address0),
    .data_symb1_M_imag_V_ce0(grp_adding_pilot_Pipeline_output_arrangement_fu_171_data_symb1_M_imag_V_ce0),
    .data_symb1_M_imag_V_q0(data_symb1_M_imag_V_q0),
    .data_symb2_M_real_V_address0(grp_adding_pilot_Pipeline_output_arrangement_fu_171_data_symb2_M_real_V_address0),
    .data_symb2_M_real_V_ce0(grp_adding_pilot_Pipeline_output_arrangement_fu_171_data_symb2_M_real_V_ce0),
    .data_symb2_M_real_V_q0(data_symb2_M_real_V_q0),
    .data_symb2_M_imag_V_address0(grp_adding_pilot_Pipeline_output_arrangement_fu_171_data_symb2_M_imag_V_address0),
    .data_symb2_M_imag_V_ce0(grp_adding_pilot_Pipeline_output_arrangement_fu_171_data_symb2_M_imag_V_ce0),
    .data_symb2_M_imag_V_q0(data_symb2_M_imag_V_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_adding_pilot_Pipeline_data_symbo2_fu_163_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state9)) begin
            grp_adding_pilot_Pipeline_data_symbo2_fu_163_ap_start_reg <= 1'b1;
        end else if ((grp_adding_pilot_Pipeline_data_symbo2_fu_163_ap_ready == 1'b1)) begin
            grp_adding_pilot_Pipeline_data_symbo2_fu_163_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_adding_pilot_Pipeline_data_symbol_fu_155_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state9)) begin
            grp_adding_pilot_Pipeline_data_symbol_fu_155_ap_start_reg <= 1'b1;
        end else if ((grp_adding_pilot_Pipeline_data_symbol_fu_155_ap_ready == 1'b1)) begin
            grp_adding_pilot_Pipeline_data_symbol_fu_155_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_adding_pilot_Pipeline_initial2_fu_116_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_adding_pilot_Pipeline_initial2_fu_116_ap_start_reg <= 1'b1;
        end else if ((grp_adding_pilot_Pipeline_initial2_fu_116_ap_ready == 1'b1)) begin
            grp_adding_pilot_Pipeline_initial2_fu_116_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_adding_pilot_Pipeline_initil_upink_pilot_fu_124_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_adding_pilot_Pipeline_initil_upink_pilot_fu_124_ap_start_reg <= 1'b1;
        end else if ((grp_adding_pilot_Pipeline_initil_upink_pilot_fu_124_ap_ready == 1'b1)) begin
            grp_adding_pilot_Pipeline_initil_upink_pilot_fu_124_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_adding_pilot_Pipeline_output_arrangement_fu_171_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state11)) begin
            grp_adding_pilot_Pipeline_output_arrangement_fu_171_ap_start_reg <= 1'b1;
        end else if ((grp_adding_pilot_Pipeline_output_arrangement_fu_171_ap_ready == 1'b1)) begin
            grp_adding_pilot_Pipeline_output_arrangement_fu_171_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_adding_pilot_Pipeline_pilot_symb_fu_135_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_adding_pilot_Pipeline_pilot_symb_fu_135_ap_start_reg <= 1'b1;
        end else if ((grp_adding_pilot_Pipeline_pilot_symb_fu_135_ap_ready == 1'b1)) begin
            grp_adding_pilot_Pipeline_pilot_symb_fu_135_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_adding_pilot_Pipeline_symb_fu_143_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state7)) begin
            grp_adding_pilot_Pipeline_symb_fu_143_ap_start_reg <= 1'b1;
        end else if ((grp_adding_pilot_Pipeline_symb_fu_143_ap_ready == 1'b1)) begin
            grp_adding_pilot_Pipeline_symb_fu_143_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        user_id_reg_228 <= user_id_fu_219_p3;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state10_on_subcall_done)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

assign ap_ST_fsm_state11_blk = 1'b0;

always @ (*) begin
    if ((grp_adding_pilot_Pipeline_output_arrangement_fu_171_ap_done == 1'b0)) begin
        ap_ST_fsm_state12_blk = 1'b1;
    end else begin
        ap_ST_fsm_state12_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_adding_pilot_Pipeline_initial2_fu_116_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_adding_pilot_Pipeline_initil_upink_pilot_fu_124_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_adding_pilot_Pipeline_pilot_symb_fu_135_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((grp_adding_pilot_Pipeline_symb_fu_143_ap_done == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((((grp_adding_pilot_Pipeline_output_arrangement_fu_171_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state12)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_adding_pilot_Pipeline_output_arrangement_fu_171_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        data_symb1_M_imag_V_address0 = grp_adding_pilot_Pipeline_output_arrangement_fu_171_data_symb1_M_imag_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        data_symb1_M_imag_V_address0 = grp_adding_pilot_Pipeline_data_symbol_fu_155_data_symb1_M_imag_V_address0;
    end else begin
        data_symb1_M_imag_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        data_symb1_M_imag_V_ce0 = grp_adding_pilot_Pipeline_output_arrangement_fu_171_data_symb1_M_imag_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        data_symb1_M_imag_V_ce0 = grp_adding_pilot_Pipeline_data_symbol_fu_155_data_symb1_M_imag_V_ce0;
    end else begin
        data_symb1_M_imag_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        data_symb1_M_imag_V_ce1 = grp_adding_pilot_Pipeline_data_symbol_fu_155_data_symb1_M_imag_V_ce1;
    end else begin
        data_symb1_M_imag_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        data_symb1_M_imag_V_we0 = grp_adding_pilot_Pipeline_data_symbol_fu_155_data_symb1_M_imag_V_we0;
    end else begin
        data_symb1_M_imag_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        data_symb1_M_imag_V_we1 = grp_adding_pilot_Pipeline_data_symbol_fu_155_data_symb1_M_imag_V_we1;
    end else begin
        data_symb1_M_imag_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        data_symb1_M_real_V_address0 = grp_adding_pilot_Pipeline_output_arrangement_fu_171_data_symb1_M_real_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        data_symb1_M_real_V_address0 = grp_adding_pilot_Pipeline_data_symbol_fu_155_data_symb1_M_real_V_address0;
    end else begin
        data_symb1_M_real_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        data_symb1_M_real_V_ce0 = grp_adding_pilot_Pipeline_output_arrangement_fu_171_data_symb1_M_real_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        data_symb1_M_real_V_ce0 = grp_adding_pilot_Pipeline_data_symbol_fu_155_data_symb1_M_real_V_ce0;
    end else begin
        data_symb1_M_real_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        data_symb1_M_real_V_ce1 = grp_adding_pilot_Pipeline_data_symbol_fu_155_data_symb1_M_real_V_ce1;
    end else begin
        data_symb1_M_real_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        data_symb1_M_real_V_we0 = grp_adding_pilot_Pipeline_data_symbol_fu_155_data_symb1_M_real_V_we0;
    end else begin
        data_symb1_M_real_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        data_symb1_M_real_V_we1 = grp_adding_pilot_Pipeline_data_symbol_fu_155_data_symb1_M_real_V_we1;
    end else begin
        data_symb1_M_real_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        data_symb2_M_imag_V_address0 = grp_adding_pilot_Pipeline_output_arrangement_fu_171_data_symb2_M_imag_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        data_symb2_M_imag_V_address0 = grp_adding_pilot_Pipeline_data_symbo2_fu_163_data_symb2_M_imag_V_address0;
    end else begin
        data_symb2_M_imag_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        data_symb2_M_imag_V_ce0 = grp_adding_pilot_Pipeline_output_arrangement_fu_171_data_symb2_M_imag_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        data_symb2_M_imag_V_ce0 = grp_adding_pilot_Pipeline_data_symbo2_fu_163_data_symb2_M_imag_V_ce0;
    end else begin
        data_symb2_M_imag_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        data_symb2_M_imag_V_ce1 = grp_adding_pilot_Pipeline_data_symbo2_fu_163_data_symb2_M_imag_V_ce1;
    end else begin
        data_symb2_M_imag_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        data_symb2_M_imag_V_we0 = grp_adding_pilot_Pipeline_data_symbo2_fu_163_data_symb2_M_imag_V_we0;
    end else begin
        data_symb2_M_imag_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        data_symb2_M_imag_V_we1 = grp_adding_pilot_Pipeline_data_symbo2_fu_163_data_symb2_M_imag_V_we1;
    end else begin
        data_symb2_M_imag_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        data_symb2_M_real_V_address0 = grp_adding_pilot_Pipeline_output_arrangement_fu_171_data_symb2_M_real_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        data_symb2_M_real_V_address0 = grp_adding_pilot_Pipeline_data_symbo2_fu_163_data_symb2_M_real_V_address0;
    end else begin
        data_symb2_M_real_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        data_symb2_M_real_V_ce0 = grp_adding_pilot_Pipeline_output_arrangement_fu_171_data_symb2_M_real_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        data_symb2_M_real_V_ce0 = grp_adding_pilot_Pipeline_data_symbo2_fu_163_data_symb2_M_real_V_ce0;
    end else begin
        data_symb2_M_real_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        data_symb2_M_real_V_ce1 = grp_adding_pilot_Pipeline_data_symbo2_fu_163_data_symb2_M_real_V_ce1;
    end else begin
        data_symb2_M_real_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        data_symb2_M_real_V_we0 = grp_adding_pilot_Pipeline_data_symbo2_fu_163_data_symb2_M_real_V_we0;
    end else begin
        data_symb2_M_real_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        data_symb2_M_real_V_we1 = grp_adding_pilot_Pipeline_data_symbo2_fu_163_data_symb2_M_real_V_we1;
    end else begin
        data_symb2_M_real_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        pilot_sym_M_imag_V_address0 = grp_adding_pilot_Pipeline_output_arrangement_fu_171_pilot_sym_M_imag_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        pilot_sym_M_imag_V_address0 = grp_adding_pilot_Pipeline_pilot_symb_fu_135_pilot_sym_M_imag_V_address0;
    end else begin
        pilot_sym_M_imag_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        pilot_sym_M_imag_V_ce0 = grp_adding_pilot_Pipeline_output_arrangement_fu_171_pilot_sym_M_imag_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        pilot_sym_M_imag_V_ce0 = grp_adding_pilot_Pipeline_pilot_symb_fu_135_pilot_sym_M_imag_V_ce0;
    end else begin
        pilot_sym_M_imag_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        pilot_sym_M_imag_V_ce1 = grp_adding_pilot_Pipeline_pilot_symb_fu_135_pilot_sym_M_imag_V_ce1;
    end else begin
        pilot_sym_M_imag_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        pilot_sym_M_imag_V_we0 = grp_adding_pilot_Pipeline_pilot_symb_fu_135_pilot_sym_M_imag_V_we0;
    end else begin
        pilot_sym_M_imag_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        pilot_sym_M_imag_V_we1 = grp_adding_pilot_Pipeline_pilot_symb_fu_135_pilot_sym_M_imag_V_we1;
    end else begin
        pilot_sym_M_imag_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        pilot_sym_M_real_V_address0 = grp_adding_pilot_Pipeline_output_arrangement_fu_171_pilot_sym_M_real_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        pilot_sym_M_real_V_address0 = grp_adding_pilot_Pipeline_pilot_symb_fu_135_pilot_sym_M_real_V_address0;
    end else begin
        pilot_sym_M_real_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        pilot_sym_M_real_V_ce0 = grp_adding_pilot_Pipeline_output_arrangement_fu_171_pilot_sym_M_real_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        pilot_sym_M_real_V_ce0 = grp_adding_pilot_Pipeline_pilot_symb_fu_135_pilot_sym_M_real_V_ce0;
    end else begin
        pilot_sym_M_real_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        pilot_sym_M_real_V_ce1 = grp_adding_pilot_Pipeline_pilot_symb_fu_135_pilot_sym_M_real_V_ce1;
    end else begin
        pilot_sym_M_real_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        pilot_sym_M_real_V_we0 = grp_adding_pilot_Pipeline_pilot_symb_fu_135_pilot_sym_M_real_V_we0;
    end else begin
        pilot_sym_M_real_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        pilot_sym_M_real_V_we1 = grp_adding_pilot_Pipeline_pilot_symb_fu_135_pilot_sym_M_real_V_we1;
    end else begin
        pilot_sym_M_real_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        pilot_vle_M_imag_V_address0 = grp_adding_pilot_Pipeline_pilot_symb_fu_135_pilot_vle_M_imag_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        pilot_vle_M_imag_V_address0 = grp_adding_pilot_Pipeline_initil_upink_pilot_fu_124_pilot_vle_M_imag_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        pilot_vle_M_imag_V_address0 = grp_adding_pilot_Pipeline_initial2_fu_116_pilot_vle_M_imag_V_address0;
    end else begin
        pilot_vle_M_imag_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        pilot_vle_M_imag_V_ce0 = grp_adding_pilot_Pipeline_pilot_symb_fu_135_pilot_vle_M_imag_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        pilot_vle_M_imag_V_ce0 = grp_adding_pilot_Pipeline_initil_upink_pilot_fu_124_pilot_vle_M_imag_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        pilot_vle_M_imag_V_ce0 = grp_adding_pilot_Pipeline_initial2_fu_116_pilot_vle_M_imag_V_ce0;
    end else begin
        pilot_vle_M_imag_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        pilot_vle_M_imag_V_d0 = grp_adding_pilot_Pipeline_initil_upink_pilot_fu_124_pilot_vle_M_imag_V_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        pilot_vle_M_imag_V_d0 = grp_adding_pilot_Pipeline_initial2_fu_116_pilot_vle_M_imag_V_d0;
    end else begin
        pilot_vle_M_imag_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        pilot_vle_M_imag_V_we0 = grp_adding_pilot_Pipeline_initil_upink_pilot_fu_124_pilot_vle_M_imag_V_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        pilot_vle_M_imag_V_we0 = grp_adding_pilot_Pipeline_initial2_fu_116_pilot_vle_M_imag_V_we0;
    end else begin
        pilot_vle_M_imag_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        pilot_vle_M_real_V_address0 = grp_adding_pilot_Pipeline_pilot_symb_fu_135_pilot_vle_M_real_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        pilot_vle_M_real_V_address0 = grp_adding_pilot_Pipeline_initil_upink_pilot_fu_124_pilot_vle_M_real_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        pilot_vle_M_real_V_address0 = grp_adding_pilot_Pipeline_initial2_fu_116_pilot_vle_M_real_V_address0;
    end else begin
        pilot_vle_M_real_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        pilot_vle_M_real_V_ce0 = grp_adding_pilot_Pipeline_pilot_symb_fu_135_pilot_vle_M_real_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        pilot_vle_M_real_V_ce0 = grp_adding_pilot_Pipeline_initil_upink_pilot_fu_124_pilot_vle_M_real_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        pilot_vle_M_real_V_ce0 = grp_adding_pilot_Pipeline_initial2_fu_116_pilot_vle_M_real_V_ce0;
    end else begin
        pilot_vle_M_real_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        pilot_vle_M_real_V_d0 = grp_adding_pilot_Pipeline_initil_upink_pilot_fu_124_pilot_vle_M_real_V_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        pilot_vle_M_real_V_d0 = grp_adding_pilot_Pipeline_initial2_fu_116_pilot_vle_M_real_V_d0;
    end else begin
        pilot_vle_M_real_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        pilot_vle_M_real_V_we0 = grp_adding_pilot_Pipeline_initil_upink_pilot_fu_124_pilot_vle_M_real_V_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        pilot_vle_M_real_V_we0 = grp_adding_pilot_Pipeline_initial2_fu_116_pilot_vle_M_real_V_we0;
    end else begin
        pilot_vle_M_real_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        symb1_M_imag_V_address0 = grp_adding_pilot_Pipeline_data_symbol_fu_155_symb1_M_imag_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        symb1_M_imag_V_address0 = grp_adding_pilot_Pipeline_symb_fu_143_symb1_M_imag_V_address0;
    end else begin
        symb1_M_imag_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        symb1_M_imag_V_ce0 = grp_adding_pilot_Pipeline_data_symbol_fu_155_symb1_M_imag_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        symb1_M_imag_V_ce0 = grp_adding_pilot_Pipeline_symb_fu_143_symb1_M_imag_V_ce0;
    end else begin
        symb1_M_imag_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        symb1_M_imag_V_we0 = grp_adding_pilot_Pipeline_symb_fu_143_symb1_M_imag_V_we0;
    end else begin
        symb1_M_imag_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        symb1_M_real_V_address0 = grp_adding_pilot_Pipeline_data_symbol_fu_155_symb1_M_real_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        symb1_M_real_V_address0 = grp_adding_pilot_Pipeline_symb_fu_143_symb1_M_real_V_address0;
    end else begin
        symb1_M_real_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        symb1_M_real_V_ce0 = grp_adding_pilot_Pipeline_data_symbol_fu_155_symb1_M_real_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        symb1_M_real_V_ce0 = grp_adding_pilot_Pipeline_symb_fu_143_symb1_M_real_V_ce0;
    end else begin
        symb1_M_real_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        symb1_M_real_V_we0 = grp_adding_pilot_Pipeline_symb_fu_143_symb1_M_real_V_we0;
    end else begin
        symb1_M_real_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        symb2_M_imag_V_address0 = grp_adding_pilot_Pipeline_data_symbo2_fu_163_symb2_M_imag_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        symb2_M_imag_V_address0 = grp_adding_pilot_Pipeline_symb_fu_143_symb2_M_imag_V_address0;
    end else begin
        symb2_M_imag_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        symb2_M_imag_V_ce0 = grp_adding_pilot_Pipeline_data_symbo2_fu_163_symb2_M_imag_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        symb2_M_imag_V_ce0 = grp_adding_pilot_Pipeline_symb_fu_143_symb2_M_imag_V_ce0;
    end else begin
        symb2_M_imag_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        symb2_M_imag_V_we0 = grp_adding_pilot_Pipeline_symb_fu_143_symb2_M_imag_V_we0;
    end else begin
        symb2_M_imag_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        symb2_M_real_V_address0 = grp_adding_pilot_Pipeline_data_symbo2_fu_163_symb2_M_real_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        symb2_M_real_V_address0 = grp_adding_pilot_Pipeline_symb_fu_143_symb2_M_real_V_address0;
    end else begin
        symb2_M_real_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        symb2_M_real_V_ce0 = grp_adding_pilot_Pipeline_data_symbo2_fu_163_symb2_M_real_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        symb2_M_real_V_ce0 = grp_adding_pilot_Pipeline_symb_fu_143_symb2_M_real_V_ce0;
    end else begin
        symb2_M_real_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        symb2_M_real_V_we0 = grp_adding_pilot_Pipeline_symb_fu_143_symb2_M_real_V_we0;
    end else begin
        symb2_M_real_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        temp1_im398_read = grp_adding_pilot_Pipeline_symb_fu_143_temp1_im398_read;
    end else begin
        temp1_im398_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        temp1_re397_read = grp_adding_pilot_Pipeline_symb_fu_143_temp1_re397_read;
    end else begin
        temp1_re397_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        temp2_im400_write = grp_adding_pilot_Pipeline_output_arrangement_fu_171_temp2_im400_write;
    end else begin
        temp2_im400_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        temp2_re399_write = grp_adding_pilot_Pipeline_output_arrangement_fu_171_temp2_re399_write;
    end else begin
        temp2_re399_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (grp_adding_pilot_Pipeline_initial2_fu_116_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((grp_adding_pilot_Pipeline_initil_upink_pilot_fu_124_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((grp_adding_pilot_Pipeline_pilot_symb_fu_135_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((grp_adding_pilot_Pipeline_symb_fu_143_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((1'b0 == ap_block_state10_on_subcall_done) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            if (((grp_adding_pilot_Pipeline_output_arrangement_fu_171_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign and_ln35_fu_197_p2 = (xor_ln27_fu_185_p2 & user_id1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state10_on_subcall_done = ((grp_adding_pilot_Pipeline_data_symbo2_fu_163_ap_done == 1'b0) | (grp_adding_pilot_Pipeline_data_symbol_fu_155_ap_done == 1'b0));
end

assign grp_adding_pilot_Pipeline_data_symbo2_fu_163_ap_start = grp_adding_pilot_Pipeline_data_symbo2_fu_163_ap_start_reg;

assign grp_adding_pilot_Pipeline_data_symbol_fu_155_ap_start = grp_adding_pilot_Pipeline_data_symbol_fu_155_ap_start_reg;

assign grp_adding_pilot_Pipeline_initial2_fu_116_ap_start = grp_adding_pilot_Pipeline_initial2_fu_116_ap_start_reg;

assign grp_adding_pilot_Pipeline_initil_upink_pilot_fu_124_ap_start = grp_adding_pilot_Pipeline_initil_upink_pilot_fu_124_ap_start_reg;

assign grp_adding_pilot_Pipeline_output_arrangement_fu_171_ap_start = grp_adding_pilot_Pipeline_output_arrangement_fu_171_ap_start_reg;

assign grp_adding_pilot_Pipeline_pilot_symb_fu_135_ap_start = grp_adding_pilot_Pipeline_pilot_symb_fu_135_ap_start_reg;

assign grp_adding_pilot_Pipeline_symb_fu_143_ap_start = grp_adding_pilot_Pipeline_symb_fu_143_ap_start_reg;

assign or_ln27_fu_191_p2 = (user_id1 | user_id0);

assign select_ln31_fu_211_p3 = ((user_id1[0:0] == 1'b1) ? select_ln35_fu_203_p3 : 2'd1);

assign select_ln35_fu_203_p3 = ((and_ln35_fu_197_p2[0:0] == 1'b1) ? 2'd2 : 2'd3);

assign temp2_im400_din = grp_adding_pilot_Pipeline_output_arrangement_fu_171_temp2_im400_din;

assign temp2_re399_din = grp_adding_pilot_Pipeline_output_arrangement_fu_171_temp2_re399_din;

assign user_id_fu_219_p3 = ((or_ln27_fu_191_p2[0:0] == 1'b1) ? select_ln31_fu_211_p3 : 2'd0);

assign xor_ln27_fu_185_p2 = (user_id0 ^ 1'd1);

endmodule //top_tx_adding_pilot
