// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module top_tx_top_tx_Pipeline_scaling_loop (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        temp2_re_dout,
        temp2_re_empty_n,
        temp2_re_read,
        temp2_im_dout,
        temp2_im_empty_n,
        temp2_im_read,
        temp5_M_real_V_address0,
        temp5_M_real_V_ce0,
        temp5_M_real_V_we0,
        temp5_M_real_V_d0,
        temp5_M_imag_V_address0,
        temp5_M_imag_V_ce0,
        temp5_M_imag_V_we0,
        temp5_M_imag_V_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] temp2_re_dout;
input   temp2_re_empty_n;
output   temp2_re_read;
input  [15:0] temp2_im_dout;
input   temp2_im_empty_n;
output   temp2_im_read;
output  [11:0] temp5_M_real_V_address0;
output   temp5_M_real_V_ce0;
output   temp5_M_real_V_we0;
output  [15:0] temp5_M_real_V_d0;
output  [11:0] temp5_M_imag_V_address0;
output   temp5_M_imag_V_ce0;
output   temp5_M_imag_V_we0;
output  [15:0] temp5_M_imag_V_d0;

reg ap_idle;
reg temp2_re_read;
reg temp2_im_read;
reg temp5_M_real_V_ce0;
reg temp5_M_real_V_we0;
reg temp5_M_imag_V_ce0;
reg temp5_M_imag_V_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln58_fu_106_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    temp2_re_blk_n;
wire    ap_block_pp0_stage0;
reg    temp2_im_blk_n;
reg   [11:0] i_1_reg_249;
reg    ap_block_pp0_stage0_11001;
wire   [63:0] i_cast_fu_123_p1;
reg   [11:0] i_fu_56;
wire   [11:0] add_ln58_fu_112_p2;
wire    ap_loop_init;
reg   [11:0] ap_sig_allocacmp_i_1;
wire   [15:0] sub_ln1303_fu_136_p2;
wire   [14:0] trunc_ln1303_1_fu_142_p4;
wire   [0:0] tmp_fu_128_p3;
wire   [14:0] sub_ln1303_1_fu_152_p2;
wire   [14:0] tmp_2_fu_158_p4;
wire   [14:0] select_ln1303_fu_168_p3;
wire   [15:0] sub_ln1303_2_fu_193_p2;
wire   [14:0] trunc_ln1303_4_fu_199_p4;
wire   [0:0] tmp_1_fu_185_p3;
wire   [14:0] sub_ln1303_3_fu_209_p2;
wire   [14:0] tmp_3_fu_215_p4;
wire   [14:0] select_ln1303_1_fu_225_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
end

top_tx_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln58_fu_106_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_56 <= add_ln58_fu_112_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_56 <= 12'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_1_reg_249 <= ap_sig_allocacmp_i_1;
    end
end

always @ (*) begin
    if (((icmp_ln58_fu_106_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_1 = 12'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_56;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        temp2_im_blk_n = temp2_im_empty_n;
    end else begin
        temp2_im_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        temp2_im_read = 1'b1;
    end else begin
        temp2_im_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        temp2_re_blk_n = temp2_re_empty_n;
    end else begin
        temp2_re_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        temp2_re_read = 1'b1;
    end else begin
        temp2_re_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        temp5_M_imag_V_ce0 = 1'b1;
    end else begin
        temp5_M_imag_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        temp5_M_imag_V_we0 = 1'b1;
    end else begin
        temp5_M_imag_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        temp5_M_real_V_ce0 = 1'b1;
    end else begin
        temp5_M_real_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        temp5_M_real_V_we0 = 1'b1;
    end else begin
        temp5_M_real_V_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln58_fu_112_p2 = (ap_sig_allocacmp_i_1 + 12'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & ((temp2_im_empty_n == 1'b0) | (temp2_re_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & ((temp2_im_empty_n == 1'b0) | (temp2_re_empty_n == 1'b0)));
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((temp2_im_empty_n == 1'b0) | (temp2_re_empty_n == 1'b0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign i_cast_fu_123_p1 = i_1_reg_249;

assign icmp_ln58_fu_106_p2 = ((ap_sig_allocacmp_i_1 == 12'd3072) ? 1'b1 : 1'b0);

assign select_ln1303_1_fu_225_p3 = ((tmp_1_fu_185_p3[0:0] == 1'b1) ? sub_ln1303_3_fu_209_p2 : tmp_3_fu_215_p4);

assign select_ln1303_fu_168_p3 = ((tmp_fu_128_p3[0:0] == 1'b1) ? sub_ln1303_1_fu_152_p2 : tmp_2_fu_158_p4);

assign sub_ln1303_1_fu_152_p2 = (15'd0 - trunc_ln1303_1_fu_142_p4);

assign sub_ln1303_2_fu_193_p2 = (16'd0 - temp2_im_dout);

assign sub_ln1303_3_fu_209_p2 = (15'd0 - trunc_ln1303_4_fu_199_p4);

assign sub_ln1303_fu_136_p2 = (16'd0 - temp2_re_dout);

assign temp5_M_imag_V_address0 = i_cast_fu_123_p1;

assign temp5_M_imag_V_d0 = {{select_ln1303_1_fu_225_p3}, {1'd0}};

assign temp5_M_real_V_address0 = i_cast_fu_123_p1;

assign temp5_M_real_V_d0 = {{select_ln1303_fu_168_p3}, {1'd0}};

assign tmp_1_fu_185_p3 = temp2_im_dout[32'd15];

assign tmp_2_fu_158_p4 = {{temp2_re_dout[15:1]}};

assign tmp_3_fu_215_p4 = {{temp2_im_dout[15:1]}};

assign tmp_fu_128_p3 = temp2_re_dout[32'd15];

assign trunc_ln1303_1_fu_142_p4 = {{sub_ln1303_fu_136_p2[15:1]}};

assign trunc_ln1303_4_fu_199_p4 = {{sub_ln1303_2_fu_193_p2[15:1]}};

endmodule //top_tx_top_tx_Pipeline_scaling_loop
