// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module top_tx_fft_top (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_M_real_address0,
        in_M_real_ce0,
        in_M_real_q0,
        in_M_imag_address0,
        in_M_imag_ce0,
        in_M_imag_q0,
        out_M_real_address0,
        out_M_real_ce0,
        out_M_real_we0,
        out_M_real_d0,
        out_M_imag_address0,
        out_M_imag_ce0,
        out_M_imag_we0,
        out_M_imag_d0
);

parameter    ap_ST_fsm_state1 = 8'd1;
parameter    ap_ST_fsm_state2 = 8'd2;
parameter    ap_ST_fsm_state3 = 8'd4;
parameter    ap_ST_fsm_state4 = 8'd8;
parameter    ap_ST_fsm_state5 = 8'd16;
parameter    ap_ST_fsm_state6 = 8'd32;
parameter    ap_ST_fsm_state7 = 8'd64;
parameter    ap_ST_fsm_state8 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [9:0] in_M_real_address0;
output   in_M_real_ce0;
input  [15:0] in_M_real_q0;
output  [9:0] in_M_imag_address0;
output   in_M_imag_ce0;
input  [15:0] in_M_imag_q0;
output  [9:0] out_M_real_address0;
output   out_M_real_ce0;
output   out_M_real_we0;
output  [14:0] out_M_real_d0;
output  [9:0] out_M_imag_address0;
output   out_M_imag_ce0;
output   out_M_imag_we0;
output  [14:0] out_M_imag_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    grp_fft_top_Pipeline_VITIS_LOOP_14_1_fu_80_ap_start;
wire    grp_fft_top_Pipeline_VITIS_LOOP_14_1_fu_80_ap_done;
wire    grp_fft_top_Pipeline_VITIS_LOOP_14_1_fu_80_ap_idle;
wire    grp_fft_top_Pipeline_VITIS_LOOP_14_1_fu_80_ap_ready;
wire   [31:0] grp_fft_top_Pipeline_VITIS_LOOP_14_1_fu_80_xn_din;
wire    grp_fft_top_Pipeline_VITIS_LOOP_14_1_fu_80_xn_write;
wire   [9:0] grp_fft_top_Pipeline_VITIS_LOOP_14_1_fu_80_in_M_real_address0;
wire    grp_fft_top_Pipeline_VITIS_LOOP_14_1_fu_80_in_M_real_ce0;
wire   [9:0] grp_fft_top_Pipeline_VITIS_LOOP_14_1_fu_80_in_M_imag_address0;
wire    grp_fft_top_Pipeline_VITIS_LOOP_14_1_fu_80_in_M_imag_ce0;
reg    grp_fft_syn_config1_s_fu_89_ap_ce;
wire    grp_fft_syn_config1_s_fu_89_ap_start;
wire    grp_fft_syn_config1_s_fu_89_ap_done;
wire    grp_fft_syn_config1_s_fu_89_ap_idle;
wire    grp_fft_syn_config1_s_fu_89_ap_ready;
wire    grp_fft_syn_config1_s_fu_89_xn_read;
wire   [31:0] grp_fft_syn_config1_s_fu_89_xk_din;
wire    grp_fft_syn_config1_s_fu_89_xk_write;
wire   [7:0] grp_fft_syn_config1_s_fu_89_status_data_V_din;
wire    grp_fft_syn_config1_s_fu_89_status_data_V_write;
wire    grp_fft_syn_config1_s_fu_89_config_ch_data_V_read;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
wire    grp_fft_top_Pipeline_VITIS_LOOP_26_1_fu_97_ap_start;
wire    grp_fft_top_Pipeline_VITIS_LOOP_26_1_fu_97_ap_done;
wire    grp_fft_top_Pipeline_VITIS_LOOP_26_1_fu_97_ap_idle;
wire    grp_fft_top_Pipeline_VITIS_LOOP_26_1_fu_97_ap_ready;
wire    grp_fft_top_Pipeline_VITIS_LOOP_26_1_fu_97_xk_read;
wire   [9:0] grp_fft_top_Pipeline_VITIS_LOOP_26_1_fu_97_out_M_real_address0;
wire    grp_fft_top_Pipeline_VITIS_LOOP_26_1_fu_97_out_M_real_ce0;
wire    grp_fft_top_Pipeline_VITIS_LOOP_26_1_fu_97_out_M_real_we0;
wire   [14:0] grp_fft_top_Pipeline_VITIS_LOOP_26_1_fu_97_out_M_real_d0;
wire   [9:0] grp_fft_top_Pipeline_VITIS_LOOP_26_1_fu_97_out_M_imag_address0;
wire    grp_fft_top_Pipeline_VITIS_LOOP_26_1_fu_97_out_M_imag_ce0;
wire    grp_fft_top_Pipeline_VITIS_LOOP_26_1_fu_97_out_M_imag_we0;
wire   [14:0] grp_fft_top_Pipeline_VITIS_LOOP_26_1_fu_97_out_M_imag_d0;
reg    grp_fft_top_Pipeline_VITIS_LOOP_14_1_fu_80_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    xn_full_n;
reg    xn_write;
reg    grp_fft_syn_config1_s_fu_89_ap_start_reg;
wire   [31:0] xn_dout;
wire    xn_empty_n;
reg    xn_read;
wire    xk_full_n;
reg    xk_write;
wire    status_s_full_n;
reg    status_s_write;
wire   [15:0] config_s_dout;
wire    config_s_empty_n;
reg    config_s_read;
reg    grp_fft_top_Pipeline_VITIS_LOOP_26_1_fu_97_ap_start_reg;
wire    ap_CS_fsm_state7;
wire   [31:0] xk_dout;
wire    xk_empty_n;
reg    xk_read;
wire    ap_CS_fsm_state8;
wire    config_s_full_n;
reg    config_s_write;
wire    ap_CS_fsm_state3;
wire   [7:0] status_s_dout;
wire    status_s_empty_n;
reg    status_s_read;
wire    ap_CS_fsm_state6;
reg   [7:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
#0 grp_fft_top_Pipeline_VITIS_LOOP_14_1_fu_80_ap_start_reg = 1'b0;
#0 grp_fft_syn_config1_s_fu_89_ap_start_reg = 1'b0;
#0 grp_fft_top_Pipeline_VITIS_LOOP_26_1_fu_97_ap_start_reg = 1'b0;
end

top_tx_fft_top_Pipeline_VITIS_LOOP_14_1 grp_fft_top_Pipeline_VITIS_LOOP_14_1_fu_80(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_fft_top_Pipeline_VITIS_LOOP_14_1_fu_80_ap_start),
    .ap_done(grp_fft_top_Pipeline_VITIS_LOOP_14_1_fu_80_ap_done),
    .ap_idle(grp_fft_top_Pipeline_VITIS_LOOP_14_1_fu_80_ap_idle),
    .ap_ready(grp_fft_top_Pipeline_VITIS_LOOP_14_1_fu_80_ap_ready),
    .xn_din(grp_fft_top_Pipeline_VITIS_LOOP_14_1_fu_80_xn_din),
    .xn_full_n(xn_full_n),
    .xn_write(grp_fft_top_Pipeline_VITIS_LOOP_14_1_fu_80_xn_write),
    .in_M_real_address0(grp_fft_top_Pipeline_VITIS_LOOP_14_1_fu_80_in_M_real_address0),
    .in_M_real_ce0(grp_fft_top_Pipeline_VITIS_LOOP_14_1_fu_80_in_M_real_ce0),
    .in_M_real_q0(in_M_real_q0),
    .in_M_imag_address0(grp_fft_top_Pipeline_VITIS_LOOP_14_1_fu_80_in_M_imag_address0),
    .in_M_imag_ce0(grp_fft_top_Pipeline_VITIS_LOOP_14_1_fu_80_in_M_imag_ce0),
    .in_M_imag_q0(in_M_imag_q0)
);

top_tx_fft_syn_config1_s grp_fft_syn_config1_s_fu_89(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_ce(grp_fft_syn_config1_s_fu_89_ap_ce),
    .ap_start(grp_fft_syn_config1_s_fu_89_ap_start),
    .ap_done(grp_fft_syn_config1_s_fu_89_ap_done),
    .ap_idle(grp_fft_syn_config1_s_fu_89_ap_idle),
    .ap_ready(grp_fft_syn_config1_s_fu_89_ap_ready),
    .xn_dout(xn_dout),
    .xn_empty_n(xn_empty_n),
    .xn_read(grp_fft_syn_config1_s_fu_89_xn_read),
    .xk_din(grp_fft_syn_config1_s_fu_89_xk_din),
    .xk_full_n(xk_full_n),
    .xk_write(grp_fft_syn_config1_s_fu_89_xk_write),
    .status_data_V_din(grp_fft_syn_config1_s_fu_89_status_data_V_din),
    .status_data_V_full_n(status_s_full_n),
    .status_data_V_write(grp_fft_syn_config1_s_fu_89_status_data_V_write),
    .config_ch_data_V_dout(config_s_dout),
    .config_ch_data_V_empty_n(config_s_empty_n),
    .config_ch_data_V_read(grp_fft_syn_config1_s_fu_89_config_ch_data_V_read)
);

top_tx_fft_top_Pipeline_VITIS_LOOP_26_1 grp_fft_top_Pipeline_VITIS_LOOP_26_1_fu_97(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_fft_top_Pipeline_VITIS_LOOP_26_1_fu_97_ap_start),
    .ap_done(grp_fft_top_Pipeline_VITIS_LOOP_26_1_fu_97_ap_done),
    .ap_idle(grp_fft_top_Pipeline_VITIS_LOOP_26_1_fu_97_ap_idle),
    .ap_ready(grp_fft_top_Pipeline_VITIS_LOOP_26_1_fu_97_ap_ready),
    .xk_dout(xk_dout),
    .xk_empty_n(xk_empty_n),
    .xk_read(grp_fft_top_Pipeline_VITIS_LOOP_26_1_fu_97_xk_read),
    .out_M_real_address0(grp_fft_top_Pipeline_VITIS_LOOP_26_1_fu_97_out_M_real_address0),
    .out_M_real_ce0(grp_fft_top_Pipeline_VITIS_LOOP_26_1_fu_97_out_M_real_ce0),
    .out_M_real_we0(grp_fft_top_Pipeline_VITIS_LOOP_26_1_fu_97_out_M_real_we0),
    .out_M_real_d0(grp_fft_top_Pipeline_VITIS_LOOP_26_1_fu_97_out_M_real_d0),
    .out_M_imag_address0(grp_fft_top_Pipeline_VITIS_LOOP_26_1_fu_97_out_M_imag_address0),
    .out_M_imag_ce0(grp_fft_top_Pipeline_VITIS_LOOP_26_1_fu_97_out_M_imag_ce0),
    .out_M_imag_we0(grp_fft_top_Pipeline_VITIS_LOOP_26_1_fu_97_out_M_imag_we0),
    .out_M_imag_d0(grp_fft_top_Pipeline_VITIS_LOOP_26_1_fu_97_out_M_imag_d0)
);

top_tx_fifo_w16_d2_S config_s_fifo_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(16'd1366),
    .if_full_n(config_s_full_n),
    .if_write(config_s_write),
    .if_dout(config_s_dout),
    .if_empty_n(config_s_empty_n),
    .if_read(config_s_read)
);

top_tx_fifo_w8_d2_S status_s_fifo_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(grp_fft_syn_config1_s_fu_89_status_data_V_din),
    .if_full_n(status_s_full_n),
    .if_write(status_s_write),
    .if_dout(status_s_dout),
    .if_empty_n(status_s_empty_n),
    .if_read(status_s_read)
);

top_tx_fifo_w32_d1024_A xn_fifo_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(grp_fft_top_Pipeline_VITIS_LOOP_14_1_fu_80_xn_din),
    .if_full_n(xn_full_n),
    .if_write(xn_write),
    .if_dout(xn_dout),
    .if_empty_n(xn_empty_n),
    .if_read(xn_read)
);

top_tx_fifo_w32_d1024_A xk_fifo_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(grp_fft_syn_config1_s_fu_89_xk_din),
    .if_full_n(xk_full_n),
    .if_write(xk_write),
    .if_dout(xk_dout),
    .if_empty_n(xk_empty_n),
    .if_read(xk_read)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_fft_syn_config1_s_fu_89_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_fft_syn_config1_s_fu_89_ap_start_reg <= 1'b1;
        end else if ((grp_fft_syn_config1_s_fu_89_ap_ready == 1'b1)) begin
            grp_fft_syn_config1_s_fu_89_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_fft_top_Pipeline_VITIS_LOOP_14_1_fu_80_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_fft_top_Pipeline_VITIS_LOOP_14_1_fu_80_ap_start_reg <= 1'b1;
        end else if ((grp_fft_top_Pipeline_VITIS_LOOP_14_1_fu_80_ap_ready == 1'b1)) begin
            grp_fft_top_Pipeline_VITIS_LOOP_14_1_fu_80_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_fft_top_Pipeline_VITIS_LOOP_26_1_fu_97_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state7)) begin
            grp_fft_top_Pipeline_VITIS_LOOP_26_1_fu_97_ap_start_reg <= 1'b1;
        end else if ((grp_fft_top_Pipeline_VITIS_LOOP_26_1_fu_97_ap_ready == 1'b1)) begin
            grp_fft_top_Pipeline_VITIS_LOOP_26_1_fu_97_ap_start_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_fft_top_Pipeline_VITIS_LOOP_14_1_fu_80_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((config_s_full_n == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_fft_syn_config1_s_fu_89_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if ((status_s_empty_n == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((grp_fft_top_Pipeline_VITIS_LOOP_26_1_fu_97_ap_done == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)) | ((1'b1 == ap_CS_fsm_state8) & (grp_fft_top_Pipeline_VITIS_LOOP_26_1_fu_97_ap_done == 1'b1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) & (grp_fft_top_Pipeline_VITIS_LOOP_26_1_fu_97_ap_done == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        config_s_read = grp_fft_syn_config1_s_fu_89_config_ch_data_V_read;
    end else begin
        config_s_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (config_s_full_n == 1'b1))) begin
        config_s_write = 1'b1;
    end else begin
        config_s_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        grp_fft_syn_config1_s_fu_89_ap_ce = 1'b1;
    end else begin
        grp_fft_syn_config1_s_fu_89_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (status_s_empty_n == 1'b1))) begin
        status_s_read = 1'b1;
    end else begin
        status_s_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        status_s_write = grp_fft_syn_config1_s_fu_89_status_data_V_write;
    end else begin
        status_s_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        xk_read = grp_fft_top_Pipeline_VITIS_LOOP_26_1_fu_97_xk_read;
    end else begin
        xk_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        xk_write = grp_fft_syn_config1_s_fu_89_xk_write;
    end else begin
        xk_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        xn_read = grp_fft_syn_config1_s_fu_89_xn_read;
    end else begin
        xn_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        xn_write = grp_fft_top_Pipeline_VITIS_LOOP_14_1_fu_80_xn_write;
    end else begin
        xn_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_fft_top_Pipeline_VITIS_LOOP_14_1_fu_80_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (config_s_full_n == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((grp_fft_syn_config1_s_fu_89_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (status_s_empty_n == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & (grp_fft_top_Pipeline_VITIS_LOOP_26_1_fu_97_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign grp_fft_syn_config1_s_fu_89_ap_start = grp_fft_syn_config1_s_fu_89_ap_start_reg;

assign grp_fft_top_Pipeline_VITIS_LOOP_14_1_fu_80_ap_start = grp_fft_top_Pipeline_VITIS_LOOP_14_1_fu_80_ap_start_reg;

assign grp_fft_top_Pipeline_VITIS_LOOP_26_1_fu_97_ap_start = grp_fft_top_Pipeline_VITIS_LOOP_26_1_fu_97_ap_start_reg;

assign in_M_imag_address0 = grp_fft_top_Pipeline_VITIS_LOOP_14_1_fu_80_in_M_imag_address0;

assign in_M_imag_ce0 = grp_fft_top_Pipeline_VITIS_LOOP_14_1_fu_80_in_M_imag_ce0;

assign in_M_real_address0 = grp_fft_top_Pipeline_VITIS_LOOP_14_1_fu_80_in_M_real_address0;

assign in_M_real_ce0 = grp_fft_top_Pipeline_VITIS_LOOP_14_1_fu_80_in_M_real_ce0;

assign out_M_imag_address0 = grp_fft_top_Pipeline_VITIS_LOOP_26_1_fu_97_out_M_imag_address0;

assign out_M_imag_ce0 = grp_fft_top_Pipeline_VITIS_LOOP_26_1_fu_97_out_M_imag_ce0;

assign out_M_imag_d0 = grp_fft_top_Pipeline_VITIS_LOOP_26_1_fu_97_out_M_imag_d0;

assign out_M_imag_we0 = grp_fft_top_Pipeline_VITIS_LOOP_26_1_fu_97_out_M_imag_we0;

assign out_M_real_address0 = grp_fft_top_Pipeline_VITIS_LOOP_26_1_fu_97_out_M_real_address0;

assign out_M_real_ce0 = grp_fft_top_Pipeline_VITIS_LOOP_26_1_fu_97_out_M_real_ce0;

assign out_M_real_d0 = grp_fft_top_Pipeline_VITIS_LOOP_26_1_fu_97_out_M_real_d0;

assign out_M_real_we0 = grp_fft_top_Pipeline_VITIS_LOOP_26_1_fu_97_out_M_real_we0;

endmodule //top_tx_fft_top
