// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module top_tx_mods_Pipeline_mods_call_funct (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        temp1_re397_din,
        temp1_re397_full_n,
        temp1_re397_write,
        temp1_im398_din,
        temp1_im398_full_n,
        temp1_im398_write,
        input1_buff_V_address0,
        input1_buff_V_ce0,
        input1_buff_V_q0,
        input2_buff_V_address0,
        input2_buff_V_ce0,
        input2_buff_V_q0,
        brmerge189,
        input3_buff_V_address0,
        input3_buff_V_ce0,
        input3_buff_V_q0,
        input3_buff_V_address1,
        input3_buff_V_ce1,
        input3_buff_V_q1,
        input4_buff_V_address0,
        input4_buff_V_ce0,
        input4_buff_V_q0,
        input4_buff_V_address1,
        input4_buff_V_ce1,
        input4_buff_V_q1,
        brmerge191,
        input5_buff_V_address0,
        input5_buff_V_ce0,
        input5_buff_V_q0,
        input6_buff_V_address0,
        input6_buff_V_ce0,
        input6_buff_V_q0,
        brmerge193
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [15:0] temp1_re397_din;
input   temp1_re397_full_n;
output   temp1_re397_write;
output  [15:0] temp1_im398_din;
input   temp1_im398_full_n;
output   temp1_im398_write;
output  [10:0] input1_buff_V_address0;
output   input1_buff_V_ce0;
input  [0:0] input1_buff_V_q0;
output  [10:0] input2_buff_V_address0;
output   input2_buff_V_ce0;
input  [0:0] input2_buff_V_q0;
input  [0:0] brmerge189;
output  [10:0] input3_buff_V_address0;
output   input3_buff_V_ce0;
input  [0:0] input3_buff_V_q0;
output  [10:0] input3_buff_V_address1;
output   input3_buff_V_ce1;
input  [0:0] input3_buff_V_q1;
output  [10:0] input4_buff_V_address0;
output   input4_buff_V_ce0;
input  [0:0] input4_buff_V_q0;
output  [10:0] input4_buff_V_address1;
output   input4_buff_V_ce1;
input  [0:0] input4_buff_V_q1;
input  [0:0] brmerge191;
output  [10:0] input5_buff_V_address0;
output   input5_buff_V_ce0;
input  [0:0] input5_buff_V_q0;
output  [10:0] input6_buff_V_address0;
output   input6_buff_V_ce0;
input  [0:0] input6_buff_V_q0;
input  [0:0] brmerge193;

reg ap_idle;
reg[15:0] temp1_re397_din;
reg temp1_re397_write;
reg[15:0] temp1_im398_din;
reg temp1_im398_write;
reg[10:0] input1_buff_V_address0;
reg input1_buff_V_ce0;
reg[10:0] input2_buff_V_address0;
reg input2_buff_V_ce0;
reg input3_buff_V_ce0;
reg input3_buff_V_ce1;
reg input4_buff_V_ce0;
reg input4_buff_V_ce1;
reg input5_buff_V_ce0;
reg input6_buff_V_ce0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_enable_reg_pp0_iter19;
reg    ap_enable_reg_pp0_iter20;
reg    ap_enable_reg_pp0_iter21;
reg    ap_enable_reg_pp0_iter22;
reg    ap_enable_reg_pp0_iter23;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
reg    ap_predicate_op86_write_state2;
reg    ap_predicate_op87_write_state2;
reg    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
wire    ap_block_state12_pp0_stage0_iter11;
wire    ap_block_state13_pp0_stage0_iter12;
wire    ap_block_state14_pp0_stage0_iter13;
wire    ap_block_state15_pp0_stage0_iter14;
wire    ap_block_state16_pp0_stage0_iter15;
wire    ap_block_state17_pp0_stage0_iter16;
wire    ap_block_state18_pp0_stage0_iter17;
wire    ap_block_state19_pp0_stage0_iter18;
wire    grp_qpsk_fu_240_temp1_re397_blk_n;
wire    grp_qpsk_fu_240_temp1_im398_blk_n;
reg    ap_block_state20_pp0_stage0_iter19;
wire    ap_block_state21_pp0_stage0_iter20;
wire    ap_block_state22_pp0_stage0_iter21;
wire    ap_block_state23_pp0_stage0_iter22;
wire    grp_qam16_fu_274_temp1_re397_blk_n;
wire    grp_qam16_fu_274_temp1_im398_blk_n;
reg    ap_predicate_op152_call_state24;
wire    grp_qam64_fu_252_temp1_re397_blk_n;
wire    grp_qam64_fu_252_temp1_im398_blk_n;
reg    ap_predicate_op154_call_state24;
reg    ap_block_state24_pp0_stage0_iter23;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln119_fu_296_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    temp1_re397_blk_n;
wire    ap_block_pp0_stage0;
reg    temp1_im398_blk_n;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] brmerge191_read_read_fu_78_p2;
wire   [0:0] brmerge189_read_read_fu_84_p2;
wire   [63:0] i_4_cast_fu_308_p1;
reg   [63:0] i_4_cast_reg_350;
wire   [10:0] input1_buff_V_addr_1_gep_fu_132_p3;
wire   [10:0] input2_buff_V_addr_1_gep_fu_140_p3;
wire   [10:0] input1_buff_V_addr_2_gep_fu_148_p3;
wire   [10:0] input2_buff_V_addr_2_gep_fu_156_p3;
reg   [0:0] input1_buff_V_load_1_reg_406;
reg   [0:0] input2_buff_V_load_1_reg_411;
wire    grp_qpsk_fu_240_ap_start;
wire    grp_qpsk_fu_240_ap_done;
wire    grp_qpsk_fu_240_ap_idle;
wire    grp_qpsk_fu_240_ap_ready;
wire   [15:0] grp_qpsk_fu_240_temp1_re397_din;
wire    grp_qpsk_fu_240_temp1_re397_write;
wire   [15:0] grp_qpsk_fu_240_temp1_im398_din;
wire    grp_qpsk_fu_240_temp1_im398_write;
reg    grp_qpsk_fu_240_ap_ce;
wire    ap_block_state1_pp0_stage0_iter0_ignore_call4;
reg    ap_block_state2_pp0_stage0_iter1_ignore_call4;
wire    ap_block_state3_pp0_stage0_iter2_ignore_call4;
wire    ap_block_state4_pp0_stage0_iter3_ignore_call4;
wire    ap_block_state5_pp0_stage0_iter4_ignore_call4;
wire    ap_block_state6_pp0_stage0_iter5_ignore_call4;
wire    ap_block_state7_pp0_stage0_iter6_ignore_call4;
wire    ap_block_state8_pp0_stage0_iter7_ignore_call4;
wire    ap_block_state9_pp0_stage0_iter8_ignore_call4;
wire    ap_block_state10_pp0_stage0_iter9_ignore_call4;
wire    ap_block_state11_pp0_stage0_iter10_ignore_call4;
wire    ap_block_state12_pp0_stage0_iter11_ignore_call4;
wire    ap_block_state13_pp0_stage0_iter12_ignore_call4;
wire    ap_block_state14_pp0_stage0_iter13_ignore_call4;
wire    ap_block_state15_pp0_stage0_iter14_ignore_call4;
wire    ap_block_state16_pp0_stage0_iter15_ignore_call4;
wire    ap_block_state17_pp0_stage0_iter16_ignore_call4;
wire    ap_block_state18_pp0_stage0_iter17_ignore_call4;
wire    ap_block_state19_pp0_stage0_iter18_ignore_call4;
wire    ap_block_state20_pp0_stage0_iter19_ignore_call4;
wire    ap_block_state21_pp0_stage0_iter20_ignore_call4;
wire    ap_block_state22_pp0_stage0_iter21_ignore_call4;
wire    ap_block_state23_pp0_stage0_iter22_ignore_call4;
reg    ap_block_state24_pp0_stage0_iter23_ignore_call4;
reg    ap_block_pp0_stage0_11001_ignoreCallOp72;
wire    grp_qam64_fu_252_ap_start;
wire    grp_qam64_fu_252_ap_done;
wire    grp_qam64_fu_252_ap_idle;
wire    grp_qam64_fu_252_ap_ready;
wire   [15:0] grp_qam64_fu_252_temp1_re397_din;
wire    grp_qam64_fu_252_temp1_re397_write;
wire   [15:0] grp_qam64_fu_252_temp1_im398_din;
wire    grp_qam64_fu_252_temp1_im398_write;
reg    grp_qam64_fu_252_ap_ce;
reg    ap_predicate_op85_call_state2;
wire    ap_block_state1_pp0_stage0_iter0_ignore_call12;
reg    ap_block_state2_pp0_stage0_iter1_ignore_call12;
wire    ap_block_state3_pp0_stage0_iter2_ignore_call12;
wire    ap_block_state4_pp0_stage0_iter3_ignore_call12;
wire    ap_block_state5_pp0_stage0_iter4_ignore_call12;
wire    ap_block_state6_pp0_stage0_iter5_ignore_call12;
wire    ap_block_state7_pp0_stage0_iter6_ignore_call12;
wire    ap_block_state8_pp0_stage0_iter7_ignore_call12;
wire    ap_block_state9_pp0_stage0_iter8_ignore_call12;
wire    ap_block_state10_pp0_stage0_iter9_ignore_call12;
wire    ap_block_state11_pp0_stage0_iter10_ignore_call12;
wire    ap_block_state12_pp0_stage0_iter11_ignore_call12;
wire    ap_block_state13_pp0_stage0_iter12_ignore_call12;
wire    ap_block_state14_pp0_stage0_iter13_ignore_call12;
wire    ap_block_state15_pp0_stage0_iter14_ignore_call12;
wire    ap_block_state16_pp0_stage0_iter15_ignore_call12;
wire    ap_block_state17_pp0_stage0_iter16_ignore_call12;
wire    ap_block_state18_pp0_stage0_iter17_ignore_call12;
wire    ap_block_state19_pp0_stage0_iter18_ignore_call12;
reg    ap_block_state20_pp0_stage0_iter19_ignore_call12;
wire    ap_block_state21_pp0_stage0_iter20_ignore_call12;
wire    ap_block_state22_pp0_stage0_iter21_ignore_call12;
wire    ap_block_state23_pp0_stage0_iter22_ignore_call12;
reg    ap_block_state24_pp0_stage0_iter23_ignore_call12;
reg    ap_block_pp0_stage0_11001_ignoreCallOp85;
wire    grp_qam16_fu_274_ap_start;
wire    grp_qam16_fu_274_ap_done;
wire    grp_qam16_fu_274_ap_idle;
wire    grp_qam16_fu_274_ap_ready;
wire   [15:0] grp_qam16_fu_274_temp1_re397_din;
wire    grp_qam16_fu_274_temp1_re397_write;
wire   [15:0] grp_qam16_fu_274_temp1_im398_din;
wire    grp_qam16_fu_274_temp1_im398_write;
reg    grp_qam16_fu_274_ap_ce;
reg    ap_predicate_op92_call_state3;
wire    ap_block_state1_pp0_stage0_iter0_ignore_call8;
reg    ap_block_state2_pp0_stage0_iter1_ignore_call8;
wire    ap_block_state3_pp0_stage0_iter2_ignore_call8;
wire    ap_block_state4_pp0_stage0_iter3_ignore_call8;
wire    ap_block_state5_pp0_stage0_iter4_ignore_call8;
wire    ap_block_state6_pp0_stage0_iter5_ignore_call8;
wire    ap_block_state7_pp0_stage0_iter6_ignore_call8;
wire    ap_block_state8_pp0_stage0_iter7_ignore_call8;
wire    ap_block_state9_pp0_stage0_iter8_ignore_call8;
wire    ap_block_state10_pp0_stage0_iter9_ignore_call8;
wire    ap_block_state11_pp0_stage0_iter10_ignore_call8;
wire    ap_block_state12_pp0_stage0_iter11_ignore_call8;
wire    ap_block_state13_pp0_stage0_iter12_ignore_call8;
wire    ap_block_state14_pp0_stage0_iter13_ignore_call8;
wire    ap_block_state15_pp0_stage0_iter14_ignore_call8;
wire    ap_block_state16_pp0_stage0_iter15_ignore_call8;
wire    ap_block_state17_pp0_stage0_iter16_ignore_call8;
wire    ap_block_state18_pp0_stage0_iter17_ignore_call8;
wire    ap_block_state19_pp0_stage0_iter18_ignore_call8;
reg    ap_block_state20_pp0_stage0_iter19_ignore_call8;
wire    ap_block_state21_pp0_stage0_iter20_ignore_call8;
wire    ap_block_state22_pp0_stage0_iter21_ignore_call8;
wire    ap_block_state23_pp0_stage0_iter22_ignore_call8;
reg    ap_block_state24_pp0_stage0_iter23_ignore_call8;
reg    ap_block_pp0_stage0_11001_ignoreCallOp92;
reg    grp_qpsk_fu_240_ap_start_reg;
reg    grp_qam64_fu_252_ap_start_reg;
reg    ap_predicate_op85_call_state2_state1;
reg    grp_qam16_fu_274_ap_start_reg;
reg    ap_predicate_op92_call_state3_state2;
reg   [10:0] i_fu_68;
wire   [10:0] add_ln119_fu_302_p2;
wire    ap_loop_init;
reg   [10:0] ap_sig_allocacmp_i_3;
reg    ap_block_pp0_stage0_01001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg    ap_loop_exit_ready_pp0_iter15_reg;
reg    ap_loop_exit_ready_pp0_iter16_reg;
reg    ap_loop_exit_ready_pp0_iter17_reg;
reg    ap_loop_exit_ready_pp0_iter18_reg;
reg    ap_loop_exit_ready_pp0_iter19_reg;
reg    ap_loop_exit_ready_pp0_iter20_reg;
reg    ap_loop_exit_ready_pp0_iter21_reg;
reg    ap_loop_exit_ready_pp0_iter22_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_708;
reg    ap_condition_858;
reg    ap_condition_867;
reg    ap_condition_870;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter19 = 1'b0;
#0 ap_enable_reg_pp0_iter20 = 1'b0;
#0 ap_enable_reg_pp0_iter21 = 1'b0;
#0 ap_enable_reg_pp0_iter22 = 1'b0;
#0 ap_enable_reg_pp0_iter23 = 1'b0;
#0 grp_qpsk_fu_240_ap_start_reg = 1'b0;
#0 grp_qam64_fu_252_ap_start_reg = 1'b0;
#0 grp_qam16_fu_274_ap_start_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

top_tx_qpsk grp_qpsk_fu_240(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_qpsk_fu_240_ap_start),
    .ap_done(grp_qpsk_fu_240_ap_done),
    .ap_idle(grp_qpsk_fu_240_ap_idle),
    .ap_ready(grp_qpsk_fu_240_ap_ready),
    .temp1_re397_din(grp_qpsk_fu_240_temp1_re397_din),
    .temp1_re397_full_n(temp1_re397_full_n),
    .temp1_re397_write(grp_qpsk_fu_240_temp1_re397_write),
    .temp1_im398_din(grp_qpsk_fu_240_temp1_im398_din),
    .temp1_im398_full_n(temp1_im398_full_n),
    .temp1_im398_write(grp_qpsk_fu_240_temp1_im398_write),
    .ap_ce(grp_qpsk_fu_240_ap_ce),
    .input1(input1_buff_V_q0),
    .input2(input2_buff_V_q0),
    .temp1_re397_blk_n(grp_qpsk_fu_240_temp1_re397_blk_n),
    .temp1_im398_blk_n(grp_qpsk_fu_240_temp1_im398_blk_n)
);

top_tx_qam64 grp_qam64_fu_252(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_qam64_fu_252_ap_start),
    .ap_done(grp_qam64_fu_252_ap_done),
    .ap_idle(grp_qam64_fu_252_ap_idle),
    .ap_ready(grp_qam64_fu_252_ap_ready),
    .temp1_re397_din(grp_qam64_fu_252_temp1_re397_din),
    .temp1_re397_full_n(temp1_re397_full_n),
    .temp1_re397_write(grp_qam64_fu_252_temp1_re397_write),
    .temp1_im398_din(grp_qam64_fu_252_temp1_im398_din),
    .temp1_im398_full_n(temp1_im398_full_n),
    .temp1_im398_write(grp_qam64_fu_252_temp1_im398_write),
    .ap_ce(grp_qam64_fu_252_ap_ce),
    .input1(input1_buff_V_q0),
    .input2(input2_buff_V_q0),
    .input3(input3_buff_V_q1),
    .input4(input4_buff_V_q1),
    .input5(input5_buff_V_q0),
    .input6(input6_buff_V_q0),
    .temp1_re397_blk_n(grp_qam64_fu_252_temp1_re397_blk_n),
    .temp1_im398_blk_n(grp_qam64_fu_252_temp1_im398_blk_n)
);

top_tx_qam16 grp_qam16_fu_274(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_qam16_fu_274_ap_start),
    .ap_done(grp_qam16_fu_274_ap_done),
    .ap_idle(grp_qam16_fu_274_ap_idle),
    .ap_ready(grp_qam16_fu_274_ap_ready),
    .temp1_re397_din(grp_qam16_fu_274_temp1_re397_din),
    .temp1_re397_full_n(temp1_re397_full_n),
    .temp1_re397_write(grp_qam16_fu_274_temp1_re397_write),
    .temp1_im398_din(grp_qam16_fu_274_temp1_im398_din),
    .temp1_im398_full_n(temp1_im398_full_n),
    .temp1_im398_write(grp_qam16_fu_274_temp1_im398_write),
    .ap_ce(grp_qam16_fu_274_ap_ce),
    .input1(input1_buff_V_load_1_reg_406),
    .input2(input2_buff_V_load_1_reg_411),
    .input3(input3_buff_V_q0),
    .input4(input4_buff_V_q0),
    .temp1_re397_blk_n(grp_qam16_fu_274_temp1_re397_blk_n),
    .temp1_im398_blk_n(grp_qam16_fu_274_temp1_im398_blk_n)
);

top_tx_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter22_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter19 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter20 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter21 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter22 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter22 <= ap_enable_reg_pp0_iter21;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter23 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter23 <= ap_enable_reg_pp0_iter22;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_qam16_fu_274_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_predicate_op92_call_state3_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
            grp_qam16_fu_274_ap_start_reg <= 1'b1;
        end else if ((grp_qam16_fu_274_ap_ready == 1'b1)) begin
            grp_qam16_fu_274_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_qam64_fu_252_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_predicate_op85_call_state2_state1 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
            grp_qam64_fu_252_ap_start_reg <= 1'b1;
        end else if ((grp_qam64_fu_252_ap_ready == 1'b1)) begin
            grp_qam64_fu_252_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_qpsk_fu_240_ap_start_reg <= 1'b0;
    end else begin
        if (((brmerge189_read_read_fu_84_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
            grp_qpsk_fu_240_ap_start_reg <= 1'b1;
        end else if ((grp_qpsk_fu_240_ap_ready == 1'b1)) begin
            grp_qpsk_fu_240_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln119_fu_296_p2 == 1'd0))) begin
            i_fu_68 <= add_ln119_fu_302_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_68 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
        ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
        ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
        ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
        ap_loop_exit_ready_pp0_iter18_reg <= ap_loop_exit_ready_pp0_iter17_reg;
        ap_loop_exit_ready_pp0_iter19_reg <= ap_loop_exit_ready_pp0_iter18_reg;
        ap_loop_exit_ready_pp0_iter20_reg <= ap_loop_exit_ready_pp0_iter19_reg;
        ap_loop_exit_ready_pp0_iter21_reg <= ap_loop_exit_ready_pp0_iter20_reg;
        ap_loop_exit_ready_pp0_iter22_reg <= ap_loop_exit_ready_pp0_iter21_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln119_fu_296_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        i_4_cast_reg_350[10 : 0] <= i_4_cast_fu_308_p1[10 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (brmerge191 == 1'd0) & (brmerge189 == 1'd1))) begin
        input1_buff_V_load_1_reg_406 <= input1_buff_V_q0;
        input2_buff_V_load_1_reg_411 <= input2_buff_V_q0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln119_fu_296_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter22_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter23 == 1'b0) & (ap_enable_reg_pp0_iter22 == 1'b0) & (ap_enable_reg_pp0_iter21 == 1'b0) & (ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_i_3 = 11'd0;
    end else begin
        ap_sig_allocacmp_i_3 = i_fu_68;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp92))) begin
        grp_qam16_fu_274_ap_ce = 1'b1;
    end else begin
        grp_qam16_fu_274_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp85))) begin
        grp_qam64_fu_252_ap_ce = 1'b1;
    end else begin
        grp_qam64_fu_252_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp72))) begin
        grp_qpsk_fu_240_ap_ce = 1'b1;
    end else begin
        grp_qpsk_fu_240_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_858)) begin
        if ((1'b1 == ap_condition_708)) begin
            input1_buff_V_address0 = input1_buff_V_addr_2_gep_fu_148_p3;
        end else if (((brmerge189 == 1'd1) & (brmerge191_read_read_fu_78_p2 == 1'd0))) begin
            input1_buff_V_address0 = input1_buff_V_addr_1_gep_fu_132_p3;
        end else if ((brmerge189_read_read_fu_84_p2 == 1'd0)) begin
            input1_buff_V_address0 = i_4_cast_fu_308_p1;
        end else begin
            input1_buff_V_address0 = 'bx;
        end
    end else begin
        input1_buff_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((brmerge189 == 1'd1) & (brmerge191 == 1'd1) & (brmerge193 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln119_fu_296_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((brmerge189 == 1'd1) & (brmerge191_read_read_fu_78_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln119_fu_296_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((brmerge189_read_read_fu_84_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln119_fu_296_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        input1_buff_V_ce0 = 1'b1;
    end else begin
        input1_buff_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_858)) begin
        if ((1'b1 == ap_condition_708)) begin
            input2_buff_V_address0 = input2_buff_V_addr_2_gep_fu_156_p3;
        end else if (((brmerge189 == 1'd1) & (brmerge191_read_read_fu_78_p2 == 1'd0))) begin
            input2_buff_V_address0 = input2_buff_V_addr_1_gep_fu_140_p3;
        end else if ((brmerge189_read_read_fu_84_p2 == 1'd0)) begin
            input2_buff_V_address0 = i_4_cast_fu_308_p1;
        end else begin
            input2_buff_V_address0 = 'bx;
        end
    end else begin
        input2_buff_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((brmerge189 == 1'd1) & (brmerge191 == 1'd1) & (brmerge193 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln119_fu_296_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((brmerge189 == 1'd1) & (brmerge191_read_read_fu_78_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln119_fu_296_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((brmerge189_read_read_fu_84_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln119_fu_296_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        input2_buff_V_ce0 = 1'b1;
    end else begin
        input2_buff_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        input3_buff_V_ce0 = 1'b1;
    end else begin
        input3_buff_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        input3_buff_V_ce1 = 1'b1;
    end else begin
        input3_buff_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        input4_buff_V_ce0 = 1'b1;
    end else begin
        input4_buff_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        input4_buff_V_ce1 = 1'b1;
    end else begin
        input4_buff_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        input5_buff_V_ce0 = 1'b1;
    end else begin
        input5_buff_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        input6_buff_V_ce0 = 1'b1;
    end else begin
        input6_buff_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0)) begin
        if ((1'b1 == ap_condition_867)) begin
            temp1_im398_blk_n = temp1_im398_full_n;
        end else if (((ap_enable_reg_pp0_iter23 == 1'b1) & (ap_predicate_op154_call_state24 == 1'b1))) begin
            temp1_im398_blk_n = grp_qam64_fu_252_temp1_im398_blk_n;
        end else if (((ap_enable_reg_pp0_iter23 == 1'b1) & (ap_predicate_op152_call_state24 == 1'b1))) begin
            temp1_im398_blk_n = grp_qam16_fu_274_temp1_im398_blk_n;
        end else if (((ap_enable_reg_pp0_iter19 == 1'b1) & (brmerge189 == 1'd0))) begin
            temp1_im398_blk_n = grp_qpsk_fu_240_temp1_im398_blk_n;
        end else begin
            temp1_im398_blk_n = 1'b1;
        end
    end else begin
        temp1_im398_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_01001) & (ap_predicate_op87_write_state2 == 1'b1))) begin
        temp1_im398_din = 16'd0;
    end else if (((ap_enable_reg_pp0_iter23 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (ap_predicate_op152_call_state24 == 1'b1))) begin
        temp1_im398_din = grp_qam16_fu_274_temp1_im398_din;
    end else if (((ap_enable_reg_pp0_iter23 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (ap_predicate_op154_call_state24 == 1'b1))) begin
        temp1_im398_din = grp_qam64_fu_252_temp1_im398_din;
    end else if (((ap_enable_reg_pp0_iter19 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (brmerge189 == 1'd0))) begin
        temp1_im398_din = grp_qpsk_fu_240_temp1_im398_din;
    end else begin
        temp1_im398_din = grp_qam16_fu_274_temp1_im398_din;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op87_write_state2 == 1'b1))) begin
        temp1_im398_write = 1'b1;
    end else if (((ap_enable_reg_pp0_iter23 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (ap_predicate_op152_call_state24 == 1'b1))) begin
        temp1_im398_write = grp_qam16_fu_274_temp1_im398_write;
    end else if (((ap_enable_reg_pp0_iter23 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (ap_predicate_op154_call_state24 == 1'b1))) begin
        temp1_im398_write = grp_qam64_fu_252_temp1_im398_write;
    end else if (((ap_enable_reg_pp0_iter19 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (brmerge189 == 1'd0))) begin
        temp1_im398_write = grp_qpsk_fu_240_temp1_im398_write;
    end else begin
        temp1_im398_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0)) begin
        if ((1'b1 == ap_condition_870)) begin
            temp1_re397_blk_n = temp1_re397_full_n;
        end else if (((ap_enable_reg_pp0_iter23 == 1'b1) & (ap_predicate_op154_call_state24 == 1'b1))) begin
            temp1_re397_blk_n = grp_qam64_fu_252_temp1_re397_blk_n;
        end else if (((ap_enable_reg_pp0_iter23 == 1'b1) & (ap_predicate_op152_call_state24 == 1'b1))) begin
            temp1_re397_blk_n = grp_qam16_fu_274_temp1_re397_blk_n;
        end else if (((ap_enable_reg_pp0_iter19 == 1'b1) & (brmerge189 == 1'd0))) begin
            temp1_re397_blk_n = grp_qpsk_fu_240_temp1_re397_blk_n;
        end else begin
            temp1_re397_blk_n = 1'b1;
        end
    end else begin
        temp1_re397_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_01001) & (ap_predicate_op86_write_state2 == 1'b1))) begin
        temp1_re397_din = 16'd0;
    end else if (((ap_enable_reg_pp0_iter23 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (ap_predicate_op152_call_state24 == 1'b1))) begin
        temp1_re397_din = grp_qam16_fu_274_temp1_re397_din;
    end else if (((ap_enable_reg_pp0_iter23 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (ap_predicate_op154_call_state24 == 1'b1))) begin
        temp1_re397_din = grp_qam64_fu_252_temp1_re397_din;
    end else if (((ap_enable_reg_pp0_iter19 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (brmerge189 == 1'd0))) begin
        temp1_re397_din = grp_qpsk_fu_240_temp1_re397_din;
    end else begin
        temp1_re397_din = grp_qam16_fu_274_temp1_re397_din;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op86_write_state2 == 1'b1))) begin
        temp1_re397_write = 1'b1;
    end else if (((ap_enable_reg_pp0_iter23 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (ap_predicate_op152_call_state24 == 1'b1))) begin
        temp1_re397_write = grp_qam16_fu_274_temp1_re397_write;
    end else if (((ap_enable_reg_pp0_iter23 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (ap_predicate_op154_call_state24 == 1'b1))) begin
        temp1_re397_write = grp_qam64_fu_252_temp1_re397_write;
    end else if (((ap_enable_reg_pp0_iter19 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (brmerge189 == 1'd0))) begin
        temp1_re397_write = grp_qpsk_fu_240_temp1_re397_write;
    end else begin
        temp1_re397_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln119_fu_302_p2 = (ap_sig_allocacmp_i_3 + 11'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter23 == 1'b1) & (((ap_predicate_op154_call_state24 == 1'b1) & ((grp_qam64_fu_252_temp1_im398_blk_n == 1'b0) | (grp_qam64_fu_252_temp1_re397_blk_n == 1'b0))) | ((ap_predicate_op152_call_state24 == 1'b1) & ((grp_qam16_fu_274_temp1_im398_blk_n == 1'b0) | (grp_qam16_fu_274_temp1_re397_blk_n == 1'b0))))) | ((ap_enable_reg_pp0_iter19 == 1'b1) & (brmerge189 == 1'd0) & ((grp_qpsk_fu_240_temp1_im398_blk_n == 1'b0) | (grp_qpsk_fu_240_temp1_re397_blk_n == 1'b0))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((ap_predicate_op87_write_state2 == 1'b1) & (temp1_im398_full_n == 1'b0)) | ((temp1_re397_full_n == 1'b0) & (ap_predicate_op86_write_state2 == 1'b1)))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter23 == 1'b1) & (((ap_predicate_op154_call_state24 == 1'b1) & ((grp_qam64_fu_252_temp1_im398_blk_n == 1'b0) | (grp_qam64_fu_252_temp1_re397_blk_n == 1'b0))) | ((ap_predicate_op152_call_state24 == 1'b1) & ((grp_qam16_fu_274_temp1_im398_blk_n == 1'b0) | (grp_qam16_fu_274_temp1_re397_blk_n == 1'b0))))) | ((ap_enable_reg_pp0_iter19 == 1'b1) & (brmerge189 == 1'd0) & ((grp_qpsk_fu_240_temp1_im398_blk_n == 1'b0) | (grp_qpsk_fu_240_temp1_re397_blk_n == 1'b0))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((ap_predicate_op87_write_state2 == 1'b1) & (temp1_im398_full_n == 1'b0)) | ((temp1_re397_full_n == 1'b0) & (ap_predicate_op86_write_state2 == 1'b1)))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp72 = (((ap_enable_reg_pp0_iter23 == 1'b1) & (((ap_predicate_op154_call_state24 == 1'b1) & ((grp_qam64_fu_252_temp1_im398_blk_n == 1'b0) | (grp_qam64_fu_252_temp1_re397_blk_n == 1'b0))) | ((ap_predicate_op152_call_state24 == 1'b1) & ((grp_qam16_fu_274_temp1_im398_blk_n == 1'b0) | (grp_qam16_fu_274_temp1_re397_blk_n == 1'b0))))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((ap_predicate_op87_write_state2 == 1'b1) & (temp1_im398_full_n == 1'b0)) | ((temp1_re397_full_n == 1'b0) & (ap_predicate_op86_write_state2 == 1'b1)))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp85 = (((ap_enable_reg_pp0_iter23 == 1'b1) & (ap_predicate_op152_call_state24 == 1'b1) & ((grp_qam16_fu_274_temp1_im398_blk_n == 1'b0) | (grp_qam16_fu_274_temp1_re397_blk_n == 1'b0))) | ((ap_enable_reg_pp0_iter19 == 1'b1) & (brmerge189 == 1'd0) & ((grp_qpsk_fu_240_temp1_im398_blk_n == 1'b0) | (grp_qpsk_fu_240_temp1_re397_blk_n == 1'b0))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((ap_predicate_op87_write_state2 == 1'b1) & (temp1_im398_full_n == 1'b0)) | ((temp1_re397_full_n == 1'b0) & (ap_predicate_op86_write_state2 == 1'b1)))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp92 = (((ap_enable_reg_pp0_iter23 == 1'b1) & (ap_predicate_op154_call_state24 == 1'b1) & ((grp_qam64_fu_252_temp1_im398_blk_n == 1'b0) | (grp_qam64_fu_252_temp1_re397_blk_n == 1'b0))) | ((ap_enable_reg_pp0_iter19 == 1'b1) & (brmerge189 == 1'd0) & ((grp_qpsk_fu_240_temp1_im398_blk_n == 1'b0) | (grp_qpsk_fu_240_temp1_re397_blk_n == 1'b0))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((ap_predicate_op87_write_state2 == 1'b1) & (temp1_im398_full_n == 1'b0)) | ((temp1_re397_full_n == 1'b0) & (ap_predicate_op86_write_state2 == 1'b1)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter23 == 1'b1) & (((ap_predicate_op154_call_state24 == 1'b1) & ((grp_qam64_fu_252_temp1_im398_blk_n == 1'b0) | (grp_qam64_fu_252_temp1_re397_blk_n == 1'b0))) | ((ap_predicate_op152_call_state24 == 1'b1) & ((grp_qam16_fu_274_temp1_im398_blk_n == 1'b0) | (grp_qam16_fu_274_temp1_re397_blk_n == 1'b0))))) | ((ap_enable_reg_pp0_iter19 == 1'b1) & (brmerge189 == 1'd0) & ((grp_qpsk_fu_240_temp1_im398_blk_n == 1'b0) | (grp_qpsk_fu_240_temp1_re397_blk_n == 1'b0))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((ap_predicate_op87_write_state2 == 1'b1) & (temp1_im398_full_n == 1'b0)) | ((temp1_re397_full_n == 1'b0) & (ap_predicate_op86_write_state2 == 1'b1)))));
end

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter9_ignore_call12 = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter9_ignore_call4 = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter9_ignore_call8 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10_ignore_call12 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10_ignore_call4 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10_ignore_call8 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11_ignore_call12 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11_ignore_call4 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11_ignore_call8 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter12_ignore_call12 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter12_ignore_call4 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter12_ignore_call8 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter13_ignore_call12 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter13_ignore_call4 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter13_ignore_call8 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter14 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter14_ignore_call12 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter14_ignore_call4 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter14_ignore_call8 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter15 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter15_ignore_call12 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter15_ignore_call4 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter15_ignore_call8 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter16 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter16_ignore_call12 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter16_ignore_call4 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter16_ignore_call8 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage0_iter17 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage0_iter17_ignore_call12 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage0_iter17_ignore_call4 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage0_iter17_ignore_call8 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage0_iter18 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage0_iter18_ignore_call12 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage0_iter18_ignore_call4 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage0_iter18_ignore_call8 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0_ignore_call12 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0_ignore_call4 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0_ignore_call8 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state20_pp0_stage0_iter19 = ((brmerge189 == 1'd0) & ((grp_qpsk_fu_240_temp1_im398_blk_n == 1'b0) | (grp_qpsk_fu_240_temp1_re397_blk_n == 1'b0)));
end

always @ (*) begin
    ap_block_state20_pp0_stage0_iter19_ignore_call12 = ((brmerge189 == 1'd0) & ((grp_qpsk_fu_240_temp1_im398_blk_n == 1'b0) | (grp_qpsk_fu_240_temp1_re397_blk_n == 1'b0)));
end

assign ap_block_state20_pp0_stage0_iter19_ignore_call4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state20_pp0_stage0_iter19_ignore_call8 = ((brmerge189 == 1'd0) & ((grp_qpsk_fu_240_temp1_im398_blk_n == 1'b0) | (grp_qpsk_fu_240_temp1_re397_blk_n == 1'b0)));
end

assign ap_block_state21_pp0_stage0_iter20 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage0_iter20_ignore_call12 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage0_iter20_ignore_call4 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage0_iter20_ignore_call8 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp0_stage0_iter21 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp0_stage0_iter21_ignore_call12 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp0_stage0_iter21_ignore_call4 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp0_stage0_iter21_ignore_call8 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp0_stage0_iter22 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp0_stage0_iter22_ignore_call12 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp0_stage0_iter22_ignore_call4 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp0_stage0_iter22_ignore_call8 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state24_pp0_stage0_iter23 = (((ap_predicate_op154_call_state24 == 1'b1) & ((grp_qam64_fu_252_temp1_im398_blk_n == 1'b0) | (grp_qam64_fu_252_temp1_re397_blk_n == 1'b0))) | ((ap_predicate_op152_call_state24 == 1'b1) & ((grp_qam16_fu_274_temp1_im398_blk_n == 1'b0) | (grp_qam16_fu_274_temp1_re397_blk_n == 1'b0))));
end

always @ (*) begin
    ap_block_state24_pp0_stage0_iter23_ignore_call12 = ((ap_predicate_op152_call_state24 == 1'b1) & ((grp_qam16_fu_274_temp1_im398_blk_n == 1'b0) | (grp_qam16_fu_274_temp1_re397_blk_n == 1'b0)));
end

always @ (*) begin
    ap_block_state24_pp0_stage0_iter23_ignore_call4 = (((ap_predicate_op154_call_state24 == 1'b1) & ((grp_qam64_fu_252_temp1_im398_blk_n == 1'b0) | (grp_qam64_fu_252_temp1_re397_blk_n == 1'b0))) | ((ap_predicate_op152_call_state24 == 1'b1) & ((grp_qam16_fu_274_temp1_im398_blk_n == 1'b0) | (grp_qam16_fu_274_temp1_re397_blk_n == 1'b0))));
end

always @ (*) begin
    ap_block_state24_pp0_stage0_iter23_ignore_call8 = ((ap_predicate_op154_call_state24 == 1'b1) & ((grp_qam64_fu_252_temp1_im398_blk_n == 1'b0) | (grp_qam64_fu_252_temp1_re397_blk_n == 1'b0)));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (((ap_predicate_op87_write_state2 == 1'b1) & (temp1_im398_full_n == 1'b0)) | ((temp1_re397_full_n == 1'b0) & (ap_predicate_op86_write_state2 == 1'b1)));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1_ignore_call12 = (((ap_predicate_op87_write_state2 == 1'b1) & (temp1_im398_full_n == 1'b0)) | ((temp1_re397_full_n == 1'b0) & (ap_predicate_op86_write_state2 == 1'b1)));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1_ignore_call4 = (((ap_predicate_op87_write_state2 == 1'b1) & (temp1_im398_full_n == 1'b0)) | ((temp1_re397_full_n == 1'b0) & (ap_predicate_op86_write_state2 == 1'b1)));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1_ignore_call8 = (((ap_predicate_op87_write_state2 == 1'b1) & (temp1_im398_full_n == 1'b0)) | ((temp1_re397_full_n == 1'b0) & (ap_predicate_op86_write_state2 == 1'b1)));
end

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2_ignore_call12 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2_ignore_call4 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2_ignore_call8 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3_ignore_call12 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3_ignore_call4 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3_ignore_call8 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4_ignore_call12 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4_ignore_call4 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4_ignore_call8 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5_ignore_call12 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5_ignore_call4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5_ignore_call8 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6_ignore_call12 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6_ignore_call4 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6_ignore_call8 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7_ignore_call12 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7_ignore_call4 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7_ignore_call8 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8_ignore_call12 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8_ignore_call4 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8_ignore_call8 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_708 = ((brmerge189 == 1'd1) & (brmerge191 == 1'd1) & (brmerge193 == 1'd0));
end

always @ (*) begin
    ap_condition_858 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln119_fu_296_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0));
end

always @ (*) begin
    ap_condition_867 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op87_write_state2 == 1'b1));
end

always @ (*) begin
    ap_condition_870 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op86_write_state2 == 1'b1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

always @ (*) begin
    ap_predicate_op152_call_state24 = ((brmerge191 == 1'd0) & (brmerge189 == 1'd1));
end

always @ (*) begin
    ap_predicate_op154_call_state24 = ((brmerge193 == 1'd0) & (brmerge191 == 1'd1) & (brmerge189 == 1'd1));
end

always @ (*) begin
    ap_predicate_op85_call_state2 = ((brmerge193 == 1'd0) & (brmerge191 == 1'd1) & (brmerge189 == 1'd1));
end

always @ (*) begin
    ap_predicate_op85_call_state2_state1 = ((brmerge189 == 1'd1) & (brmerge191 == 1'd1) & (brmerge193 == 1'd0));
end

always @ (*) begin
    ap_predicate_op86_write_state2 = ((brmerge193 == 1'd1) & (brmerge191 == 1'd1) & (brmerge189 == 1'd1));
end

always @ (*) begin
    ap_predicate_op87_write_state2 = ((brmerge193 == 1'd1) & (brmerge191 == 1'd1) & (brmerge189 == 1'd1));
end

always @ (*) begin
    ap_predicate_op92_call_state3 = ((brmerge191 == 1'd0) & (brmerge189 == 1'd1));
end

always @ (*) begin
    ap_predicate_op92_call_state3_state2 = ((brmerge191 == 1'd0) & (brmerge189 == 1'd1));
end

assign brmerge189_read_read_fu_84_p2 = brmerge189;

assign brmerge191_read_read_fu_78_p2 = brmerge191;

assign grp_qam16_fu_274_ap_start = grp_qam16_fu_274_ap_start_reg;

assign grp_qam64_fu_252_ap_start = grp_qam64_fu_252_ap_start_reg;

assign grp_qpsk_fu_240_ap_start = grp_qpsk_fu_240_ap_start_reg;

assign i_4_cast_fu_308_p1 = ap_sig_allocacmp_i_3;

assign icmp_ln119_fu_296_p2 = ((ap_sig_allocacmp_i_3 == 11'd1200) ? 1'b1 : 1'b0);

assign input1_buff_V_addr_1_gep_fu_132_p3 = i_4_cast_fu_308_p1;

assign input1_buff_V_addr_2_gep_fu_148_p3 = i_4_cast_fu_308_p1;

assign input2_buff_V_addr_1_gep_fu_140_p3 = i_4_cast_fu_308_p1;

assign input2_buff_V_addr_2_gep_fu_156_p3 = i_4_cast_fu_308_p1;

assign input3_buff_V_address0 = i_4_cast_reg_350;

assign input3_buff_V_address1 = i_4_cast_fu_308_p1;

assign input4_buff_V_address0 = i_4_cast_reg_350;

assign input4_buff_V_address1 = i_4_cast_fu_308_p1;

assign input5_buff_V_address0 = i_4_cast_fu_308_p1;

assign input6_buff_V_address0 = i_4_cast_fu_308_p1;

always @ (posedge ap_clk) begin
    i_4_cast_reg_350[63:11] <= 53'b00000000000000000000000000000000000000000000000000000;
end

endmodule //top_tx_mods_Pipeline_mods_call_funct
