// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module top_tx_top_tx_Pipeline_output_stream (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        cp_outre_TREADY,
        cp_outim_TREADY,
        cp_out_re_V_address0,
        cp_out_re_V_ce0,
        cp_out_re_V_q0,
        cp_out_re_V_1_address0,
        cp_out_re_V_1_ce0,
        cp_out_re_V_1_q0,
        cp_out_re_V_2_address0,
        cp_out_re_V_2_ce0,
        cp_out_re_V_2_q0,
        cp_out_re_V_4_address0,
        cp_out_re_V_4_ce0,
        cp_out_re_V_4_q0,
        cp_out_re_V_5_address0,
        cp_out_re_V_5_ce0,
        cp_out_re_V_5_q0,
        cp_out_re_V_6_address0,
        cp_out_re_V_6_ce0,
        cp_out_re_V_6_q0,
        cp_outre_TDATA,
        cp_outre_TVALID,
        cp_out_im_V_address0,
        cp_out_im_V_ce0,
        cp_out_im_V_q0,
        cp_out_im_V_1_address0,
        cp_out_im_V_1_ce0,
        cp_out_im_V_1_q0,
        cp_out_im_V_2_address0,
        cp_out_im_V_2_ce0,
        cp_out_im_V_2_q0,
        cp_out_im_V_4_address0,
        cp_out_im_V_4_ce0,
        cp_out_im_V_4_q0,
        cp_out_im_V_5_address0,
        cp_out_im_V_5_ce0,
        cp_out_im_V_5_q0,
        cp_out_im_V_6_address0,
        cp_out_im_V_6_ce0,
        cp_out_im_V_6_q0,
        cp_outim_TDATA,
        cp_outim_TVALID
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   cp_outre_TREADY;
input   cp_outim_TREADY;
output  [10:0] cp_out_re_V_address0;
output   cp_out_re_V_ce0;
input  [15:0] cp_out_re_V_q0;
output  [10:0] cp_out_re_V_1_address0;
output   cp_out_re_V_1_ce0;
input  [15:0] cp_out_re_V_1_q0;
output  [10:0] cp_out_re_V_2_address0;
output   cp_out_re_V_2_ce0;
input  [15:0] cp_out_re_V_2_q0;
output  [10:0] cp_out_re_V_4_address0;
output   cp_out_re_V_4_ce0;
input  [0:0] cp_out_re_V_4_q0;
output  [10:0] cp_out_re_V_5_address0;
output   cp_out_re_V_5_ce0;
input  [0:0] cp_out_re_V_5_q0;
output  [10:0] cp_out_re_V_6_address0;
output   cp_out_re_V_6_ce0;
input  [0:0] cp_out_re_V_6_q0;
output  [15:0] cp_outre_TDATA;
output   cp_outre_TVALID;
output  [10:0] cp_out_im_V_address0;
output   cp_out_im_V_ce0;
input  [15:0] cp_out_im_V_q0;
output  [10:0] cp_out_im_V_1_address0;
output   cp_out_im_V_1_ce0;
input  [15:0] cp_out_im_V_1_q0;
output  [10:0] cp_out_im_V_2_address0;
output   cp_out_im_V_2_ce0;
input  [15:0] cp_out_im_V_2_q0;
output  [10:0] cp_out_im_V_4_address0;
output   cp_out_im_V_4_ce0;
input  [0:0] cp_out_im_V_4_q0;
output  [10:0] cp_out_im_V_5_address0;
output   cp_out_im_V_5_ce0;
input  [0:0] cp_out_im_V_5_q0;
output  [10:0] cp_out_im_V_6_address0;
output   cp_out_im_V_6_ce0;
input  [0:0] cp_out_im_V_6_q0;
output  [15:0] cp_outim_TDATA;
output   cp_outim_TVALID;

reg ap_idle;
reg cp_out_re_V_ce0;
reg cp_out_re_V_1_ce0;
reg cp_out_re_V_2_ce0;
reg cp_out_re_V_4_ce0;
reg cp_out_re_V_5_ce0;
reg cp_out_re_V_6_ce0;
reg cp_outre_TVALID;
reg cp_out_im_V_ce0;
reg cp_out_im_V_1_ce0;
reg cp_out_im_V_2_ce0;
reg cp_out_im_V_4_ce0;
reg cp_out_im_V_5_ce0;
reg cp_out_im_V_6_ce0;
reg cp_outim_TVALID;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_state2_io;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln145_fu_280_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    cp_outre_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg    cp_outim_TDATA_blk_n;
reg    ap_block_pp0_stage0_11001;
wire   [63:0] zext_ln147_fu_315_p1;
reg   [12:0] phi_urem8_fu_80;
wire   [12:0] select_ln145_fu_307_p3;
wire    ap_loop_init;
reg   [12:0] ap_sig_allocacmp_phi_urem8_load;
reg   [26:0] phi_mul6_fu_84;
wire   [26:0] add_ln147_fu_344_p2;
reg   [12:0] i_fu_88;
wire   [12:0] add_ln145_fu_286_p2;
reg   [12:0] ap_sig_allocacmp_i_2;
wire   [15:0] p_s_fu_372_p9;
reg    ap_block_pp0_stage0_01001;
wire   [15:0] p_0_fu_405_p9;
wire   [12:0] add_ln145_1_fu_295_p2;
wire   [0:0] icmp_ln145_1_fu_301_p2;
wire   [15:0] p_s_fu_372_p5;
wire   [15:0] p_s_fu_372_p6;
wire   [15:0] p_s_fu_372_p7;
wire   [2:0] p_s_fu_372_p8;
wire   [15:0] p_0_fu_405_p5;
wire   [15:0] p_0_fu_405_p6;
wire   [15:0] p_0_fu_405_p7;
wire   [2:0] p_0_fu_405_p8;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
end

top_tx_mux_73_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 16 ),
    .din5_WIDTH( 16 ),
    .din6_WIDTH( 16 ),
    .din7_WIDTH( 3 ),
    .dout_WIDTH( 16 ))
mux_73_16_1_1_U182(
    .din0(cp_out_re_V_q0),
    .din1(cp_out_re_V_1_q0),
    .din2(cp_out_re_V_2_q0),
    .din3(16'd0),
    .din4(p_s_fu_372_p5),
    .din5(p_s_fu_372_p6),
    .din6(p_s_fu_372_p7),
    .din7(p_s_fu_372_p8),
    .dout(p_s_fu_372_p9)
);

top_tx_mux_73_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 16 ),
    .din5_WIDTH( 16 ),
    .din6_WIDTH( 16 ),
    .din7_WIDTH( 3 ),
    .dout_WIDTH( 16 ))
mux_73_16_1_1_U183(
    .din0(cp_out_im_V_q0),
    .din1(cp_out_im_V_1_q0),
    .din2(cp_out_im_V_2_q0),
    .din3(16'd0),
    .din4(p_0_fu_405_p5),
    .din5(p_0_fu_405_p6),
    .din6(p_0_fu_405_p7),
    .din7(p_0_fu_405_p8),
    .dout(p_0_fu_405_p9)
);

top_tx_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln145_fu_280_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_88 <= add_ln145_fu_286_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_88 <= 13'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            phi_mul6_fu_84 <= 27'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            phi_mul6_fu_84 <= add_ln147_fu_344_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln145_fu_280_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            phi_urem8_fu_80 <= select_ln145_fu_307_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            phi_urem8_fu_80 <= 13'd0;
        end
    end
end

always @ (*) begin
    if (((icmp_ln145_fu_280_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_2 = 13'd0;
    end else begin
        ap_sig_allocacmp_i_2 = i_fu_88;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_phi_urem8_load = 13'd0;
    end else begin
        ap_sig_allocacmp_phi_urem8_load = phi_urem8_fu_80;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        cp_out_im_V_1_ce0 = 1'b1;
    end else begin
        cp_out_im_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        cp_out_im_V_2_ce0 = 1'b1;
    end else begin
        cp_out_im_V_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        cp_out_im_V_4_ce0 = 1'b1;
    end else begin
        cp_out_im_V_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        cp_out_im_V_5_ce0 = 1'b1;
    end else begin
        cp_out_im_V_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        cp_out_im_V_6_ce0 = 1'b1;
    end else begin
        cp_out_im_V_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        cp_out_im_V_ce0 = 1'b1;
    end else begin
        cp_out_im_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        cp_out_re_V_1_ce0 = 1'b1;
    end else begin
        cp_out_re_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        cp_out_re_V_2_ce0 = 1'b1;
    end else begin
        cp_out_re_V_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        cp_out_re_V_4_ce0 = 1'b1;
    end else begin
        cp_out_re_V_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        cp_out_re_V_5_ce0 = 1'b1;
    end else begin
        cp_out_re_V_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        cp_out_re_V_6_ce0 = 1'b1;
    end else begin
        cp_out_re_V_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        cp_out_re_V_ce0 = 1'b1;
    end else begin
        cp_out_re_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        cp_outim_TDATA_blk_n = cp_outim_TREADY;
    end else begin
        cp_outim_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        cp_outim_TVALID = 1'b1;
    end else begin
        cp_outim_TVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        cp_outre_TDATA_blk_n = cp_outre_TREADY;
    end else begin
        cp_outre_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        cp_outre_TVALID = 1'b1;
    end else begin
        cp_outre_TVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln145_1_fu_295_p2 = (ap_sig_allocacmp_phi_urem8_load + 13'd1);

assign add_ln145_fu_286_p2 = (ap_sig_allocacmp_i_2 + 13'd1);

assign add_ln147_fu_344_p2 = (phi_mul6_fu_84 + 27'd14365);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & ((cp_outim_TREADY == 1'b0) | (cp_outre_TREADY == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & ((cp_outim_TREADY == 1'b0) | (cp_outre_TREADY == 1'b0) | (1'b1 == ap_block_state2_io)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & ((cp_outim_TREADY == 1'b0) | (cp_outre_TREADY == 1'b0) | (1'b1 == ap_block_state2_io)));
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_io = ((cp_outim_TREADY == 1'b0) | (cp_outre_TREADY == 1'b0));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((cp_outim_TREADY == 1'b0) | (cp_outre_TREADY == 1'b0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign cp_out_im_V_1_address0 = zext_ln147_fu_315_p1;

assign cp_out_im_V_2_address0 = zext_ln147_fu_315_p1;

assign cp_out_im_V_4_address0 = zext_ln147_fu_315_p1;

assign cp_out_im_V_5_address0 = zext_ln147_fu_315_p1;

assign cp_out_im_V_6_address0 = zext_ln147_fu_315_p1;

assign cp_out_im_V_address0 = zext_ln147_fu_315_p1;

assign cp_out_re_V_1_address0 = zext_ln147_fu_315_p1;

assign cp_out_re_V_2_address0 = zext_ln147_fu_315_p1;

assign cp_out_re_V_4_address0 = zext_ln147_fu_315_p1;

assign cp_out_re_V_5_address0 = zext_ln147_fu_315_p1;

assign cp_out_re_V_6_address0 = zext_ln147_fu_315_p1;

assign cp_out_re_V_address0 = zext_ln147_fu_315_p1;

assign cp_outim_TDATA = p_0_fu_405_p9;

assign cp_outre_TDATA = p_s_fu_372_p9;

assign icmp_ln145_1_fu_301_p2 = ((add_ln145_1_fu_295_p2 < 13'd1168) ? 1'b1 : 1'b0);

assign icmp_ln145_fu_280_p2 = ((ap_sig_allocacmp_i_2 == 13'd8176) ? 1'b1 : 1'b0);

assign p_0_fu_405_p5 = cp_out_im_V_4_q0;

assign p_0_fu_405_p6 = cp_out_im_V_5_q0;

assign p_0_fu_405_p7 = cp_out_im_V_6_q0;

assign p_0_fu_405_p8 = {{phi_mul6_fu_84[26:24]}};

assign p_s_fu_372_p5 = cp_out_re_V_4_q0;

assign p_s_fu_372_p6 = cp_out_re_V_5_q0;

assign p_s_fu_372_p7 = cp_out_re_V_6_q0;

assign p_s_fu_372_p8 = {{phi_mul6_fu_84[26:24]}};

assign select_ln145_fu_307_p3 = ((icmp_ln145_1_fu_301_p2[0:0] == 1'b1) ? add_ln145_1_fu_295_p2 : 13'd0);

assign zext_ln147_fu_315_p1 = ap_sig_allocacmp_phi_urem8_load;

endmodule //top_tx_top_tx_Pipeline_output_stream
