// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module top_tx_mods_Pipeline_input_buff (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input1_TVALID,
        input2_TVALID,
        input3_TVALID,
        input4_TVALID,
        input5_TVALID,
        input6_TVALID,
        input1_TDATA,
        input1_TREADY,
        input1_buff_V_address0,
        input1_buff_V_ce0,
        input1_buff_V_we0,
        input1_buff_V_d0,
        input2_TDATA,
        input2_TREADY,
        input2_buff_V_address0,
        input2_buff_V_ce0,
        input2_buff_V_we0,
        input2_buff_V_d0,
        input3_TDATA,
        input3_TREADY,
        input3_buff_V_address0,
        input3_buff_V_ce0,
        input3_buff_V_we0,
        input3_buff_V_d0,
        input4_TDATA,
        input4_TREADY,
        input4_buff_V_address0,
        input4_buff_V_ce0,
        input4_buff_V_we0,
        input4_buff_V_d0,
        input5_TDATA,
        input5_TREADY,
        input5_buff_V_address0,
        input5_buff_V_ce0,
        input5_buff_V_we0,
        input5_buff_V_d0,
        input6_TDATA,
        input6_TREADY,
        input6_buff_V_address0,
        input6_buff_V_ce0,
        input6_buff_V_we0,
        input6_buff_V_d0
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   input1_TVALID;
input   input2_TVALID;
input   input3_TVALID;
input   input4_TVALID;
input   input5_TVALID;
input   input6_TVALID;
input  [7:0] input1_TDATA;
output   input1_TREADY;
output  [10:0] input1_buff_V_address0;
output   input1_buff_V_ce0;
output   input1_buff_V_we0;
output  [0:0] input1_buff_V_d0;
input  [7:0] input2_TDATA;
output   input2_TREADY;
output  [10:0] input2_buff_V_address0;
output   input2_buff_V_ce0;
output   input2_buff_V_we0;
output  [0:0] input2_buff_V_d0;
input  [7:0] input3_TDATA;
output   input3_TREADY;
output  [10:0] input3_buff_V_address0;
output   input3_buff_V_ce0;
output   input3_buff_V_we0;
output  [0:0] input3_buff_V_d0;
input  [7:0] input4_TDATA;
output   input4_TREADY;
output  [10:0] input4_buff_V_address0;
output   input4_buff_V_ce0;
output   input4_buff_V_we0;
output  [0:0] input4_buff_V_d0;
input  [7:0] input5_TDATA;
output   input5_TREADY;
output  [10:0] input5_buff_V_address0;
output   input5_buff_V_ce0;
output   input5_buff_V_we0;
output  [0:0] input5_buff_V_d0;
input  [7:0] input6_TDATA;
output   input6_TREADY;
output  [10:0] input6_buff_V_address0;
output   input6_buff_V_ce0;
output   input6_buff_V_we0;
output  [0:0] input6_buff_V_d0;

reg ap_idle;
reg input1_TREADY;
reg input1_buff_V_ce0;
reg input1_buff_V_we0;
reg input2_TREADY;
reg input2_buff_V_ce0;
reg input2_buff_V_we0;
reg input3_TREADY;
reg input3_buff_V_ce0;
reg input3_buff_V_we0;
reg input4_TREADY;
reg input4_buff_V_ce0;
reg input4_buff_V_we0;
reg input5_TREADY;
reg input5_buff_V_ce0;
reg input5_buff_V_we0;
reg input6_TREADY;
reg input6_buff_V_ce0;
reg input6_buff_V_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] icmp_ln108_fu_186_p2;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    input1_TDATA_blk_n;
reg    input2_TDATA_blk_n;
reg    input3_TDATA_blk_n;
reg    input4_TDATA_blk_n;
reg    input5_TDATA_blk_n;
reg    input6_TDATA_blk_n;
wire   [63:0] i_cast_fu_198_p1;
reg   [10:0] i_fu_60;
wire   [10:0] add_ln108_fu_192_p2;
wire    ap_loop_init;
reg   [10:0] ap_sig_allocacmp_i_4;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
reg    ap_condition_224;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_done_reg = 1'b0;
end

top_tx_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((ap_start_int == 1'b0) | ((input6_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input5_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input4_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input3_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input2_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((icmp_ln108_fu_186_p2 == 1'd0) & (input1_TVALID == 1'b0))) & (ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_224)) begin
        if ((icmp_ln108_fu_186_p2 == 1'd0)) begin
            i_fu_60 <= add_ln108_fu_192_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_60 <= 11'd0;
        end
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) | ((input6_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input5_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input4_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input3_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input2_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((icmp_ln108_fu_186_p2 == 1'd0) & (input1_TVALID == 1'b0)))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((input6_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input5_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input4_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input3_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input2_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((icmp_ln108_fu_186_p2 == 1'd0) & (input1_TVALID == 1'b0))) & (icmp_ln108_fu_186_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((input6_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input5_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input4_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input3_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input2_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((icmp_ln108_fu_186_p2 == 1'd0) & (input1_TVALID == 1'b0))) & (ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((input6_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input5_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input4_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input3_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input2_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((icmp_ln108_fu_186_p2 == 1'd0) & (input1_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_4 = 11'd0;
    end else begin
        ap_sig_allocacmp_i_4 = i_fu_60;
    end
end

always @ (*) begin
    if (((icmp_ln108_fu_186_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        input1_TDATA_blk_n = input1_TVALID;
    end else begin
        input1_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((input6_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input5_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input4_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input3_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input2_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((icmp_ln108_fu_186_p2 == 1'd0) & (input1_TVALID == 1'b0))) & (icmp_ln108_fu_186_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        input1_TREADY = 1'b1;
    end else begin
        input1_TREADY = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((input6_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input5_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input4_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input3_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input2_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((icmp_ln108_fu_186_p2 == 1'd0) & (input1_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        input1_buff_V_ce0 = 1'b1;
    end else begin
        input1_buff_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((input6_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input5_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input4_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input3_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input2_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((icmp_ln108_fu_186_p2 == 1'd0) & (input1_TVALID == 1'b0))) & (icmp_ln108_fu_186_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        input1_buff_V_we0 = 1'b1;
    end else begin
        input1_buff_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln108_fu_186_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        input2_TDATA_blk_n = input2_TVALID;
    end else begin
        input2_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((input6_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input5_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input4_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input3_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input2_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((icmp_ln108_fu_186_p2 == 1'd0) & (input1_TVALID == 1'b0))) & (icmp_ln108_fu_186_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        input2_TREADY = 1'b1;
    end else begin
        input2_TREADY = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((input6_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input5_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input4_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input3_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input2_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((icmp_ln108_fu_186_p2 == 1'd0) & (input1_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        input2_buff_V_ce0 = 1'b1;
    end else begin
        input2_buff_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((input6_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input5_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input4_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input3_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input2_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((icmp_ln108_fu_186_p2 == 1'd0) & (input1_TVALID == 1'b0))) & (icmp_ln108_fu_186_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        input2_buff_V_we0 = 1'b1;
    end else begin
        input2_buff_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln108_fu_186_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        input3_TDATA_blk_n = input3_TVALID;
    end else begin
        input3_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((input6_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input5_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input4_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input3_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input2_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((icmp_ln108_fu_186_p2 == 1'd0) & (input1_TVALID == 1'b0))) & (icmp_ln108_fu_186_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        input3_TREADY = 1'b1;
    end else begin
        input3_TREADY = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((input6_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input5_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input4_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input3_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input2_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((icmp_ln108_fu_186_p2 == 1'd0) & (input1_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        input3_buff_V_ce0 = 1'b1;
    end else begin
        input3_buff_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((input6_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input5_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input4_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input3_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input2_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((icmp_ln108_fu_186_p2 == 1'd0) & (input1_TVALID == 1'b0))) & (icmp_ln108_fu_186_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        input3_buff_V_we0 = 1'b1;
    end else begin
        input3_buff_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln108_fu_186_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        input4_TDATA_blk_n = input4_TVALID;
    end else begin
        input4_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((input6_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input5_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input4_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input3_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input2_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((icmp_ln108_fu_186_p2 == 1'd0) & (input1_TVALID == 1'b0))) & (icmp_ln108_fu_186_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        input4_TREADY = 1'b1;
    end else begin
        input4_TREADY = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((input6_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input5_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input4_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input3_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input2_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((icmp_ln108_fu_186_p2 == 1'd0) & (input1_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        input4_buff_V_ce0 = 1'b1;
    end else begin
        input4_buff_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((input6_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input5_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input4_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input3_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input2_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((icmp_ln108_fu_186_p2 == 1'd0) & (input1_TVALID == 1'b0))) & (icmp_ln108_fu_186_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        input4_buff_V_we0 = 1'b1;
    end else begin
        input4_buff_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln108_fu_186_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        input5_TDATA_blk_n = input5_TVALID;
    end else begin
        input5_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((input6_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input5_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input4_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input3_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input2_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((icmp_ln108_fu_186_p2 == 1'd0) & (input1_TVALID == 1'b0))) & (icmp_ln108_fu_186_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        input5_TREADY = 1'b1;
    end else begin
        input5_TREADY = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((input6_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input5_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input4_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input3_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input2_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((icmp_ln108_fu_186_p2 == 1'd0) & (input1_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        input5_buff_V_ce0 = 1'b1;
    end else begin
        input5_buff_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((input6_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input5_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input4_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input3_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input2_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((icmp_ln108_fu_186_p2 == 1'd0) & (input1_TVALID == 1'b0))) & (icmp_ln108_fu_186_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        input5_buff_V_we0 = 1'b1;
    end else begin
        input5_buff_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln108_fu_186_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        input6_TDATA_blk_n = input6_TVALID;
    end else begin
        input6_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((input6_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input5_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input4_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input3_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input2_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((icmp_ln108_fu_186_p2 == 1'd0) & (input1_TVALID == 1'b0))) & (icmp_ln108_fu_186_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        input6_TREADY = 1'b1;
    end else begin
        input6_TREADY = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((input6_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input5_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input4_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input3_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input2_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((icmp_ln108_fu_186_p2 == 1'd0) & (input1_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        input6_buff_V_ce0 = 1'b1;
    end else begin
        input6_buff_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((input6_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input5_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input4_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input3_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input2_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((icmp_ln108_fu_186_p2 == 1'd0) & (input1_TVALID == 1'b0))) & (icmp_ln108_fu_186_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        input6_buff_V_we0 = 1'b1;
    end else begin
        input6_buff_V_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln108_fu_192_p2 = (ap_sig_allocacmp_i_4 + 11'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start_int == 1'b0) | ((input6_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input5_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input4_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input3_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input2_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((icmp_ln108_fu_186_p2 == 1'd0) & (input1_TVALID == 1'b0)));
end

always @ (*) begin
    ap_condition_224 = (~((ap_start_int == 1'b0) | ((input6_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input5_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input4_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input3_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((input2_TVALID == 1'b0) & (icmp_ln108_fu_186_p2 == 1'd0)) | ((icmp_ln108_fu_186_p2 == 1'd0) & (input1_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign i_cast_fu_198_p1 = ap_sig_allocacmp_i_4;

assign icmp_ln108_fu_186_p2 = ((ap_sig_allocacmp_i_4 == 11'd1200) ? 1'b1 : 1'b0);

assign input1_buff_V_address0 = i_cast_fu_198_p1;

assign input1_buff_V_d0 = input1_TDATA[0:0];

assign input2_buff_V_address0 = i_cast_fu_198_p1;

assign input2_buff_V_d0 = input2_TDATA[0:0];

assign input3_buff_V_address0 = i_cast_fu_198_p1;

assign input3_buff_V_d0 = input3_TDATA[0:0];

assign input4_buff_V_address0 = i_cast_fu_198_p1;

assign input4_buff_V_d0 = input4_TDATA[0:0];

assign input5_buff_V_address0 = i_cast_fu_198_p1;

assign input5_buff_V_d0 = input5_TDATA[0:0];

assign input6_buff_V_address0 = i_cast_fu_198_p1;

assign input6_buff_V_d0 = input6_TDATA[0:0];

endmodule //top_tx_mods_Pipeline_input_buff
